{
  "name": "Bakery_Analytics",
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-PK",
    "tables": [
      {
        "name": "DimDate",
        "lineageTag": "5998267a-9b6f-4768-9003-cd7515013541",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "Date",
            "formatString": "Long Date",
            "lineageTag": "a58a909c-64a7-4a7e-9fe3-bd137509dd63",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DateKey",
            "formatString": "0",
            "lineageTag": "2d84ffe5-f654-4f72-9d9b-8d630097b361",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "formatString": "0",
            "lineageTag": "1ec590db-889c-4583-b376-292ffd04036a",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Quarter",
            "dataType": "int64",
            "sourceColumn": "Quarter",
            "formatString": "0",
            "lineageTag": "60c7fbc4-d938-44a1-975e-2402925de2f8",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Month",
            "dataType": "int64",
            "sourceColumn": "Month",
            "formatString": "0",
            "lineageTag": "57218067-9f41-4ec9-9586-682fa7048576",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Week",
            "dataType": "int64",
            "sourceColumn": "Week",
            "formatString": "0",
            "lineageTag": "a55d529f-3224-4dca-b53c-59079b6f965e",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MonthName",
            "dataType": "string",
            "sourceColumn": "MonthName",
            "lineageTag": "607ef1f3-cbca-437c-a73b-53cfe7b67f90",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MonthShort",
            "dataType": "string",
            "sourceColumn": "MonthShort",
            "sortByColumn": "Month",
            "lineageTag": "4377bc8b-3a82-4eb7-9a64-db72a9f8e850",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DayName",
            "dataType": "string",
            "sourceColumn": "DayName",
            "lineageTag": "b0c9ed23-949e-46cf-863c-f4280e3836e1",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DayShort",
            "dataType": "string",
            "sourceColumn": "DayShort",
            "lineageTag": "5d8c7c82-3416-4013-b140-56d21aec3d29",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DayOfWeek",
            "dataType": "int64",
            "sourceColumn": "DayOfWeek",
            "formatString": "0",
            "lineageTag": "a30a50fb-feb7-40e2-be29-9683f2afab6d",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DayOfMonth",
            "dataType": "int64",
            "sourceColumn": "DayOfMonth",
            "formatString": "0",
            "lineageTag": "829e304a-ff0d-49fd-938a-8896cc6c2988",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DayOfYear",
            "dataType": "int64",
            "sourceColumn": "DayOfYear",
            "formatString": "0",
            "lineageTag": "e6798db8-2110-47df-8db9-240cf25364b1",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "IsWeekend",
            "dataType": "boolean",
            "sourceColumn": "IsWeekend",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "236a2c52-90e1-4d16-945c-3fd214632c6f",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FiscalYear",
            "dataType": "int64",
            "sourceColumn": "FiscalYear",
            "formatString": "0",
            "lineageTag": "effc6f10-36d6-449b-bedc-7504542d3dfa",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FiscalQuarter",
            "dataType": "int64",
            "sourceColumn": "FiscalQuarter",
            "formatString": "0",
            "lineageTag": "896941fb-1d27-4537-af75-73c1864a3d79",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "YearMonth",
            "dataType": "string",
            "sourceColumn": "YearMonth",
            "lineageTag": "3510f0bf-49ca-4163-9107-a74279940837",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "YearMonthNum",
            "dataType": "int64",
            "sourceColumn": "YearMonthNum",
            "formatString": "0",
            "lineageTag": "ca994918-26ab-4783-aec0-64a8d3e8e666",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimDate",
            "mode": "import",
            "queryGroup": "08_Dimension Tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = let",
                "    // Define date range",
                "    StartDate = #date(2022, 1, 1),",
                "    EndDate = #date(2024, 12, 31),",
                "    ",
                "    // Calculate number of days",
                "    DayCount = Duration.Days(EndDate - StartDate) + 1,",
                "    ",
                "    // Generate list of dates",
                "    DateList = List.Dates(StartDate, DayCount, #duration(1,0,0,0)),",
                "    ",
                "    // Convert to table",
                "    TableFromList = Table.FromList(DateList, Splitter.SplitByNothing()),",
                "    RenamedColumns = Table.RenameColumns(TableFromList,{{\"Column1\", \"Date\"}}),",
                "    ChangedType = Table.TransformColumnTypes(RenamedColumns,{{\"Date\", type date}}),",
                "    ",
                "    // Add DateKey",
                "    AddDateKey = Table.AddColumn(ChangedType, \"DateKey\", each ",
                "        Date.Year([Date]) * 10000 + Date.Month([Date]) * 100 + Date.Day([Date]), ",
                "        Int64.Type),",
                "    ",
                "    // Add Year, Quarter, Month",
                "    AddYear = Table.AddColumn(AddDateKey, \"Year\", each Date.Year([Date]), Int64.Type),",
                "    AddQuarter = Table.AddColumn(AddYear, \"Quarter\", each Date.QuarterOfYear([Date]), Int64.Type),",
                "    AddMonth = Table.AddColumn(AddQuarter, \"Month\", each Date.Month([Date]), Int64.Type),",
                "    AddWeek = Table.AddColumn(AddMonth, \"Week\", each Date.WeekOfYear([Date]), Int64.Type),",
                "    ",
                "    // Add Month and Day Names",
                "    AddMonthName = Table.AddColumn(AddWeek, \"MonthName\", each Date.MonthName([Date]), type text),",
                "    AddMonthShort = Table.AddColumn(AddMonthName, \"MonthShort\", each Text.Start([MonthName], 3), type text),",
                "    AddDayName = Table.AddColumn(AddMonthShort, \"DayName\", each Date.DayOfWeekName([Date]), type text),",
                "    AddDayShort = Table.AddColumn(AddDayName, \"DayShort\", each Text.Start([DayName], 3), type text),",
                "    ",
                "    // Add Day Numbers",
                "    AddDayOfWeek = Table.AddColumn(AddDayShort, \"DayOfWeek\", each ",
                "        Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),",
                "    AddDayOfMonth = Table.AddColumn(AddDayOfWeek, \"DayOfMonth\", each Date.Day([Date]), Int64.Type),",
                "    AddDayOfYear = Table.AddColumn(AddDayOfMonth, \"DayOfYear\", each Date.DayOfYear([Date]), Int64.Type),",
                "    ",
                "    // Add IsWeekend",
                "    AddIsWeekend = Table.AddColumn(AddDayOfYear, \"IsWeekend\", each ",
                "        [DayOfWeek] >= 6, type logical),",
                "    ",
                "    // Add Fiscal Year (starts July 1)",
                "    AddFiscalYear = Table.AddColumn(AddIsWeekend, \"FiscalYear\", each ",
                "        if [Month] >= 7 then [Year] + 1 else [Year], Int64.Type),",
                "    ",
                "    AddFiscalQuarter = Table.AddColumn(AddFiscalYear, \"FiscalQuarter\", each ",
                "        if [Month] >= 7 and [Month] <= 9 then 1",
                "        else if [Month] >= 10 and [Month] <= 12 then 2",
                "        else if [Month] >= 1 and [Month] <= 3 then 3",
                "        else 4, Int64.Type),",
                "    ",
                "    // Add YearMonth for sorting",
                "    AddYearMonth = Table.AddColumn(AddFiscalQuarter, \"YearMonth\", each ",
                "        Text.From([Year]) & \"-\" & Text.PadStart(Text.From([Month]), 2, \"0\"), type text),",
                "    ",
                "    AddYearMonthNum = Table.AddColumn(AddYearMonth, \"YearMonthNum\", each ",
                "        [Year] * 100 + [Month], Int64.Type)",
                "in",
                "    AddYearMonthNum",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "FactSalesHeader",
        "lineageTag": "e3762359-3cc4-4bbc-a228-39e1d108c1c5",
        "columns": [
          {
            "name": "OrderID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "OrderID",
            "lineageTag": "159a33dd-e873-47e4-84e1-1ee63a6cdde2",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "OrderDate",
            "dataType": "dateTime",
            "sourceColumn": "OrderDate",
            "formatString": "Long Date",
            "lineageTag": "a48a81c5-d14e-48c3-a473-1bc38785e86f",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "OrderStatus",
            "dataType": "string",
            "sourceColumn": "OrderStatus",
            "lineageTag": "84fe4009-0279-4f15-b1fa-29f25abafa74",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "TotalQuantity",
            "dataType": "int64",
            "sourceColumn": "TotalQuantity",
            "formatString": "0",
            "lineageTag": "d9181152-1fd4-409e-8169-ee0562229788",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "GrossAmount",
            "dataType": "decimal",
            "sourceColumn": "GrossAmount",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "bde53dd2-6b8c-4856-bc08-27b026721434",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "TotalDiscount",
            "dataType": "decimal",
            "sourceColumn": "TotalDiscount",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "70d33d20-88bd-456f-adbf-9b32e54f866e",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "TotalTax",
            "dataType": "decimal",
            "sourceColumn": "TotalTax",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "25139ee0-36e5-4135-a412-6b1e9ecb5043",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "NetAmount",
            "dataType": "decimal",
            "sourceColumn": "NetAmount",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "c01d011e-b561-4639-bea3-b762d72fb204",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SalesHeaderKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SalesHeaderKey",
            "formatString": "0",
            "lineageTag": "cd56f1eb-5270-4eb8-b1f2-4e6594a6e76c",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustomerKey",
            "formatString": "0",
            "lineageTag": "b1fba60c-90d8-4dd5-9411-0b6b53fda75f",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DateKey",
            "formatString": "0",
            "lineageTag": "f44dff21-ff28-4be6-ad1d-a74a291b2fdc",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "LocationKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "LocationKey",
            "lineageTag": "14b2a753-7ae0-43f3-9248-087f5a79c6d3",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "PaymentMethodKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PaymentMethodKey",
            "formatString": "0",
            "lineageTag": "47b971ab-5cff-4bd0-85eb-227b82f6796b",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "FactSalesHeader",
            "mode": "import",
            "queryGroup": "9_Fact Tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = stgSales_Combined,",
                "    #\"Added Custom\" = Table.AddColumn(Source, \"LineAmount\", each [Quantity] * [UnitPrice]),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Added Custom\", \"NetLineAmount\", each ([Quantity] * [UnitPrice]) - [Discount] + [Tax]),",
                "  Grouped =",
                "    Table.Group(",
                "        (#\"Added Custom1\"),",
                "        {\"OrderID\"},",
                "        {",
                "            {\"CustomerID\", each List.First([CustomerID]), type text},",
                "            {\"OrderDate\", each List.First([OrderDate]), type date},",
                "            {\"Location\", each List.First([Location]), type text},",
                "            {\"OrderStatus\", each List.First([OrderStatus]), type text},",
                "            {\"LeadTime\", each List.First([LeadTime]), Int64.Type},",
                "            {\"PaymentMethod\", each List.First([PaymentMethod]), Int64.Type},",
                "            {\"TotalQuantity\", each List.Sum([Quantity]), Int64.Type},",
                "            {\"GrossAmount\", each List.Sum([LineAmount]), type number},",
                "            {\"TotalDiscount\", each List.Sum([Discount]), type number},",
                "            {\"TotalTax\", each List.Sum([Tax]), type number},",
                "            {\"NetAmount\", each List.Sum([NetLineAmount]), type number}",
                "        }",
                "    ),",
                "    #\"Added Index\" = Table.AddIndexColumn(Grouped, \"Index\", 1, 1, Int64.Type),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Index\",{{\"Index\", \"SalesHeaderKey\"}}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Renamed Columns\",{\"SalesHeaderKey\", \"OrderID\", \"CustomerID\", \"OrderDate\", \"Location\", \"OrderStatus\", \"LeadTime\", \"TotalQuantity\", \"GrossAmount\", \"TotalDiscount\", \"TotalTax\", \"NetAmount\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Reordered Columns\",{{\"NetAmount\", Currency.Type}, {\"TotalTax\", Currency.Type}, {\"TotalDiscount\", Currency.Type}, {\"GrossAmount\", Currency.Type}}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Changed Type\", {\"CustomerID\"}, DimCustomer, {\"CustomerID\"}, \"DimCustomer\", JoinKind.LeftOuter),",
                "    #\"Expanded DimCustomer\" = Table.ExpandTableColumn(#\"Merged Queries\", \"DimCustomer\", {\"CustomerKey\"}, {\"DimCustomer.CustomerKey\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Expanded DimCustomer\",{{\"DimCustomer.CustomerKey\", \"CustomerKey\"}}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Renamed Columns1\",{\"SalesHeaderKey\", \"OrderID\", \"CustomerKey\", \"CustomerID\", \"OrderDate\", \"Location\", \"OrderStatus\", \"LeadTime\", \"TotalQuantity\", \"GrossAmount\", \"TotalDiscount\", \"TotalTax\", \"NetAmount\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Reordered Columns1\",{\"CustomerID\"}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Removed Columns\", {\"OrderDate\"}, DimDate, {\"Date\"}, \"DimDate\", JoinKind.LeftOuter),",
                "    #\"Expanded DimDate\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"DimDate\", {\"DateKey\"}, {\"DimDate.DateKey\"}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Expanded DimDate\",{{\"DimDate.DateKey\", \"DateKey\"}}),",
                "    #\"Reordered Columns2\" = Table.ReorderColumns(#\"Renamed Columns2\",{\"SalesHeaderKey\", \"OrderID\", \"CustomerKey\", \"DateKey\", \"OrderDate\", \"Location\", \"OrderStatus\", \"LeadTime\", \"TotalQuantity\", \"GrossAmount\", \"TotalDiscount\", \"TotalTax\", \"NetAmount\"}),",
                "    #\"Merged Queries2\" = Table.NestedJoin(#\"Reordered Columns2\", {\"Location\"}, DimLocation, {\"Location\"}, \"DimLocation\", JoinKind.LeftOuter),",
                "    #\"Expanded DimLocation\" = Table.ExpandTableColumn(#\"Merged Queries2\", \"DimLocation\", {\"LocationKey\"}, {\"LocationKey\"}),",
                "    #\"Reordered Columns3\" = Table.ReorderColumns(#\"Expanded DimLocation\",{\"SalesHeaderKey\", \"OrderID\", \"CustomerKey\", \"DateKey\", \"OrderDate\", \"LocationKey\", \"Location\", \"OrderStatus\", \"LeadTime\", \"TotalQuantity\", \"GrossAmount\", \"TotalDiscount\", \"TotalTax\", \"NetAmount\"}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Reordered Columns3\",{\"Location\"}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Removed Columns1\",{{\"SalesHeaderKey\", Order.Ascending}}),",
                "    #\"Reordered Columns4\" = Table.ReorderColumns(#\"Sorted Rows\",{\"SalesHeaderKey\", \"OrderID\", \"DateKey\", \"CustomerKey\", \"LocationKey\", \"OrderDate\", \"OrderStatus\", \"TotalQuantity\", \"GrossAmount\", \"TotalDiscount\", \"TotalTax\", \"NetAmount\", \"LeadTime\"}),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Reordered Columns4\",{\"LeadTime\"}),",
                "    #\"Merged Queries3\" = Table.NestedJoin(#\"Removed Columns2\", {\"PaymentMethod\"}, DimPaymentMethod, {\"PaymentMethod\"}, \"DimPaymentMethod\", JoinKind.LeftOuter),",
                "    #\"Expanded DimPaymentMethod\" = Table.ExpandTableColumn(#\"Merged Queries3\", \"DimPaymentMethod\", {\"PaymentMethodKey\"}, {\"PaymentMethodKey\"}),",
                "    #\"Reordered Columns5\" = Table.ReorderColumns(#\"Expanded DimPaymentMethod\",{\"SalesHeaderKey\", \"OrderID\", \"DateKey\", \"CustomerKey\", \"LocationKey\", \"PaymentMethodKey\", \"PaymentMethod\", \"OrderDate\", \"OrderStatus\", \"TotalQuantity\", \"GrossAmount\", \"TotalDiscount\", \"TotalTax\", \"NetAmount\"}),",
                "    #\"Removed Columns3\" = Table.RemoveColumns(#\"Reordered Columns5\",{\"PaymentMethod\"})",
                "in",
                "    #\"Removed Columns3\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ]
      },
      {
        "name": "FactSalesLine",
        "lineageTag": "ca52f063-8d8d-40a2-b96a-d93c7ca3a6c8",
        "columns": [
          {
            "name": "Quantity",
            "dataType": "int64",
            "sourceColumn": "Quantity",
            "formatString": "0",
            "lineageTag": "7f3f49f9-eebd-4522-b139-25947c765923",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "UnitPrice",
            "dataType": "decimal",
            "sourceColumn": "UnitPrice",
            "formatString": "\"Rs\"#,0.###############;-\"Rs\"#,0.###############;\"Rs\"#,0.###############",
            "lineageTag": "abbc5584-bb3e-455e-a182-9ce3b5d99a33",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-PK\"}"
              }
            ]
          },
          {
            "name": "Discount",
            "dataType": "decimal",
            "sourceColumn": "Discount",
            "formatString": "\"Rs\"#,0.###############;-\"Rs\"#,0.###############;\"Rs\"#,0.###############",
            "lineageTag": "da44a81e-2c0d-42ed-a140-a0a4ceba46af",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-PK\"}"
              }
            ]
          },
          {
            "name": "Tax",
            "dataType": "decimal",
            "sourceColumn": "Tax",
            "formatString": "\"Rs\"#,0.###############;-\"Rs\"#,0.###############;\"Rs\"#,0.###############",
            "lineageTag": "268d0a8b-1692-47eb-9859-d43cc86331c2",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-PK\"}"
              }
            ]
          },
          {
            "name": "LineAmount",
            "dataType": "decimal",
            "sourceColumn": "LineAmount",
            "formatString": "\"Rs\"#,0.###############;-\"Rs\"#,0.###############;\"Rs\"#,0.###############",
            "lineageTag": "251f3c0e-62cb-43d9-84df-8e933d5bc7e4",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-PK\"}"
              }
            ]
          },
          {
            "name": "NetLineAmount",
            "dataType": "decimal",
            "sourceColumn": "NetLineAmount",
            "formatString": "\"Rs\"#,0.###############;-\"Rs\"#,0.###############;\"Rs\"#,0.###############",
            "lineageTag": "eff911ec-d34a-4cc3-a2e1-da989fd1c67f",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-PK\"}"
              }
            ]
          },
          {
            "name": "SalesHeaderKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SalesHeaderKey",
            "formatString": "0",
            "lineageTag": "3ca19406-75dc-4194-8c4a-860766195741",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductKey",
            "formatString": "0",
            "lineageTag": "043311a9-d902-452a-8629-f9de2b845473",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DateKey",
            "formatString": "0",
            "lineageTag": "32b6c4a7-be84-4893-a898-ecfb36f66021",
            "summarizeBy": "count",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "FactSalesLine",
            "mode": "import",
            "queryGroup": "9_Fact Tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = stgSales_Combined,",
                "",
                "    #\"Added LineAmount\" =",
                "        Table.AddColumn(",
                "            Source,",
                "            \"LineAmount\",",
                "            each [Quantity] * [UnitPrice],",
                "            Currency.Type",
                "        ),",
                "",
                "    #\"Added NetLineAmount\" =",
                "        Table.AddColumn(",
                "            #\"Added LineAmount\",",
                "            \"NetLineAmount\",",
                "            each ([Quantity] * [UnitPrice]) - [Discount] + [Tax],",
                "            Currency.Type",
                "        ),",
                "",
                "    Grouped =",
                "        Table.Group(",
                "            #\"Added NetLineAmount\",",
                "            {\"OrderID\"},",
                "            {",
                "                {",
                "                    \"Data\",",
                "                    (t as table) =>",
                "                        Table.AddIndexColumn(t, \"LineNumber\", 1, 1, Int64.Type),",
                "                    type table",
                "                }",
                "            }",
                "        ),",
                "",
                "    Expanded =",
                "    Table.ExpandTableColumn(",
                "        Grouped,",
                "        \"Data\",",
                "        List.RemoveItems(",
                "            Table.ColumnNames(#\"Added NetLineAmount\"),",
                "            {\"OrderID\"}",
                "        ) & {\"LineNumber\"}",
                "    ),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Expanded,{{\"NetLineAmount\", Currency.Type}, {\"LineAmount\", Currency.Type}, {\"Tax\", Currency.Type}, {\"Discount\", Currency.Type}, {\"UnitPrice\", Currency.Type}, {\"Quantity\", Int64.Type}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Name\"}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Removed Columns\", {\"OrderID\"}, FactSalesHeader, {\"OrderID\"}, \"FactSalesHeader\", JoinKind.LeftOuter),",
                "    #\"Expanded FactSalesHeader\" = Table.ExpandTableColumn(#\"Merged Queries\", \"FactSalesHeader\", {\"SalesHeaderKey\"}, {\"SalesHeaderKey\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Expanded FactSalesHeader\",{\"SalesHeaderKey\", \"OrderID\", \"CustomerID\", \"ProductID\", \"OrderDate\", \"Quantity\", \"UnitPrice\", \"Discount\", \"Tax\", \"PaymentMethod\", \"Location\", \"LeadTime\", \"OrderStatus\", \"LineAmount\", \"NetLineAmount\", \"LineNumber\"}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Reordered Columns\", {\"CustomerID\"}, DimCustomer, {\"CustomerID\"}, \"DimCustomer\", JoinKind.LeftOuter),",
                "    #\"Expanded DimCustomer\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"DimCustomer\", {\"CustomerKey\"}, {\"CustomerKey\"}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Expanded DimCustomer\",{\"SalesHeaderKey\", \"OrderID\", \"CustomerKey\", \"CustomerID\", \"ProductID\", \"OrderDate\", \"Quantity\", \"UnitPrice\", \"Discount\", \"Tax\", \"PaymentMethod\", \"Location\", \"LeadTime\", \"OrderStatus\", \"LineAmount\", \"NetLineAmount\", \"LineNumber\"}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Reordered Columns1\",{\"CustomerID\"}),",
                "    #\"Merged Queries2\" = Table.NestedJoin(#\"Removed Columns1\", {\"ProductID\"}, DimProduct, {\"ProductID\"}, \"DimProduct\", JoinKind.LeftOuter),",
                "    #\"Expanded DimProduct\" = Table.ExpandTableColumn(#\"Merged Queries2\", \"DimProduct\", {\"ProductKey\"}, {\"ProductKey\"}),",
                "    #\"Reordered Columns2\" = Table.ReorderColumns(#\"Expanded DimProduct\",{\"SalesHeaderKey\", \"OrderID\", \"CustomerKey\", \"ProductID\", \"ProductKey\", \"OrderDate\", \"Quantity\", \"UnitPrice\", \"Discount\", \"Tax\", \"PaymentMethod\", \"Location\", \"LeadTime\", \"OrderStatus\", \"LineAmount\", \"NetLineAmount\", \"LineNumber\"}),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Reordered Columns2\",{\"ProductID\"}),",
                "    #\"Merged Queries3\" = Table.NestedJoin(#\"Removed Columns2\", {\"OrderDate\"}, DimDate, {\"Date\"}, \"DimDate\", JoinKind.LeftOuter),",
                "    #\"Expanded DimDate\" = Table.ExpandTableColumn(#\"Merged Queries3\", \"DimDate\", {\"DateKey\"}, {\"DateKey\"}),",
                "    #\"Reordered Columns3\" = Table.ReorderColumns(#\"Expanded DimDate\",{\"SalesHeaderKey\", \"OrderID\", \"DateKey\", \"ProductKey\", \"CustomerKey\", \"OrderDate\", \"Quantity\", \"UnitPrice\", \"Discount\", \"Tax\", \"PaymentMethod\", \"LineNumber\", \"Location\", \"LeadTime\", \"OrderStatus\", \"LineAmount\", \"NetLineAmount\"}),",
                "    #\"Removed Columns3\" = Table.RemoveColumns(#\"Reordered Columns3\",{\"CustomerKey\", \"OrderDate\", \"PaymentMethod\", \"LineNumber\", \"Location\", \"LeadTime\", \"OrderStatus\", \"OrderID\"})",
                "in",
                "    #\"Removed Columns3\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DimCustomer",
        "lineageTag": "86e05e39-dbb0-4502-87b9-4d1adbd76627",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustomerKey",
            "formatString": "0",
            "lineageTag": "24c89f25-46cc-4f08-822d-68269c5ee888",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CustomerID",
            "dataType": "string",
            "sourceColumn": "CustomerID",
            "lineageTag": "b001cbe0-1286-4c27-af3b-04aff173f1ba",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CustomerName",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerName",
            "lineageTag": "f37f5e60-66b5-4ac5-a624-1f5ea2614299",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CustomerType",
            "dataType": "string",
            "sourceColumn": "CustomerType",
            "lineageTag": "591e007b-54e9-44d2-8e1d-4ecd19a7b4d6",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Email",
            "dataType": "string",
            "sourceColumn": "Email",
            "lineageTag": "afcda774-8d32-4834-b3c3-2430a5b896fa",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Phone",
            "dataType": "string",
            "sourceColumn": "Phone",
            "lineageTag": "26163722-3c12-48bc-9855-b596f44efa3b",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "RegistrationDate",
            "dataType": "dateTime",
            "sourceColumn": "RegistrationDate",
            "formatString": "Long Date",
            "lineageTag": "d048a8a0-b344-4867-9de7-8b14c8cccfe7",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "IsActive",
            "dataType": "string",
            "sourceColumn": "IsActive",
            "lineageTag": "8188e5af-98e7-440d-9fef-e139d9298f92",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimCustomer",
            "mode": "import",
            "queryGroup": "08_Dimension Tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = stgCustomer_Combined",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ]
      },
      {
        "name": "DimProduct",
        "lineageTag": "059b31aa-5f4b-493f-9cc4-873a0fe9bbfe",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductKey",
            "formatString": "0",
            "lineageTag": "6940f6f0-18f5-432d-9499-e7724bec50d7",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductID",
            "dataType": "string",
            "sourceColumn": "ProductID",
            "lineageTag": "1a4f8707-4e14-4bde-930f-da54a8fc73b7",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductName",
            "dataType": "string",
            "sourceColumn": "ProductName",
            "lineageTag": "b48213be-10d6-40aa-b562-b25e70e44bdf",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category",
            "lineageTag": "d6f90e54-4025-45d4-8485-eed487ff9638",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SubCategory",
            "dataType": "string",
            "sourceColumn": "SubCategory",
            "lineageTag": "81b5699a-27ec-436c-8a93-ca8c46e7d27f",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "UnitCost",
            "dataType": "double",
            "sourceColumn": "UnitCost",
            "lineageTag": "6005d8ea-1a24-4f1c-bbee-be2531d5689d",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "CurrentPrice",
            "dataType": "double",
            "sourceColumn": "CurrentPrice",
            "lineageTag": "25fda945-5500-4e03-953f-5b425e747eea",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "IsActive",
            "dataType": "string",
            "sourceColumn": "IsActive",
            "lineageTag": "d4afd2d8-1ad6-42ad-b07e-badddddbd629",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimProduct",
            "mode": "import",
            "queryGroup": "08_Dimension Tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = stgProduct_Combined",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ]
      },
      {
        "name": "DimPaymentMethod",
        "lineageTag": "398a0994-c747-4c4c-9d71-6c4856bb4edc",
        "columns": [
          {
            "name": "PaymentMethod",
            "dataType": "string",
            "sourceColumn": "PaymentMethod",
            "lineageTag": "aeba68d7-10b4-422e-951e-6ecb183182be",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "PaymentMethodKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PaymentMethodKey",
            "formatString": "0",
            "lineageTag": "8e34b836-b2c4-481d-8310-2b1ce6971ee5",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProcessingFeeRate",
            "dataType": "decimal",
            "sourceColumn": "ProcessingFeeRate",
            "formatString": "\"Rs\"#,0.###############;-\"Rs\"#,0.###############;\"Rs\"#,0.###############",
            "lineageTag": "108ef66e-4ca0-4529-8a7a-5e2d1658bea1",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-PK\"}"
              }
            ]
          },
          {
            "name": "IsActive",
            "dataType": "string",
            "sourceColumn": "IsActive",
            "lineageTag": "a956fd3a-bcc4-4e8d-8342-ae81f22fed8f",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimPaymentMethod",
            "mode": "import",
            "queryGroup": "08_Dimension Tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #table(",
                "        {\"PaymentMethodKey\", \"PaymentMethod\", \"ProcessingFeeRate\", \"IsActive\"},",
                "        {",
                "            {1, \"Cash\", 0.00, \"Yes\"},",
                "            {2, \"Credit Card\", 0.025, \"Yes\"},",
                "            {3, \"AfterPay\", 0.025, \"Yes\"},",
                "            {4, \"Shopify\", 0.029, \"Yes\"},",
                "            {5, \"On Account\", 0.00, \"Yes\"},",
                "            {-1, \"Unknown\", 0.00, \"No\"}",
                "        }",
                "    ),",
                "",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"PaymentMethodKey\", Int64.Type}, {\"PaymentMethod\", type text}, {\"ProcessingFeeRate\", Currency.Type}, {\"IsActive\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DimLocation",
        "lineageTag": "b694c1a7-ed31-4355-a0ca-3efdcc9bac06",
        "columns": [
          {
            "name": "LocationKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "LocationKey",
            "lineageTag": "324efe88-7568-4821-a72f-1f5d148bb1d1",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Location",
            "dataType": "string",
            "sourceColumn": "Location",
            "lineageTag": "2de56540-1174-448d-be50-11f46370ac1e",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimLocation",
            "mode": "import",
            "queryGroup": "08_Dimension Tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = stgSales_Combined,",
                "",
                "    #\"Removed Columns\" = Table.RemoveColumns(",
                "        Source,",
                "        {\"Name\",\"OrderID\",\"CustomerID\",\"ProductID\",\"OrderDate\",\"Quantity\",\"UnitPrice\",\"Discount\",\"Tax\",\"PaymentMethod\",\"LeadTime\",\"OrderStatus\"}",
                "    ),",
                "",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Columns\"),",
                "",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Removed Duplicates\", \"Index\", 1, 1, Int64.Type),",
                "",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Index\",{\"Index\",\"Location\"}),",
                "",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Reordered Columns\",{{\"Index\",\"LocationKey\"}}),",
                "",
                "    // Add Unknown row",
                "    UnknownRow = #table(",
                "        {\"LocationKey\",\"Location\"},",
                "        {{-1,\"Unknown\"}}",
                "    ),",
                "",
                "    // Combine with existing table",
                "    Combined = Table.Combine({UnknownRow, #\"Renamed Columns\"})",
                "in",
                "    Combined"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ]
      },
      {
        "name": "DimExpCategory",
        "lineageTag": "7ef431ee-8179-4707-9884-2d6aff501d8f",
        "columns": [
          {
            "name": "ExpCategoryKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ExpCategoryKey",
            "formatString": "0",
            "lineageTag": "216be524-c205-4417-9532-51f81521144e",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CategoryName",
            "dataType": "string",
            "sourceColumn": "CategoryName",
            "lineageTag": "bb651815-a4b5-4158-8b76-cc7ef274430a",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimExpCategory",
            "mode": "import",
            "queryGroup": "08_Dimension Tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = stgExpenses,",
                "    #\"Removed Columns\" = Table.RemoveColumns(Source,{\"ExpenseID\", \"ExpenseAmount\", \"ExpenseDate\", \"VendorName\", \"Description\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Columns\"),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Removed Duplicates\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Index\",{\"Index\", \"CategoryName\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Reordered Columns\",{{\"Index\", \"ExpCategoryKey\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "FactPayment",
        "lineageTag": "f6ce1901-1571-47a9-86f7-31bc64e4b798",
        "columns": [
          {
            "name": "PaymentID",
            "dataType": "string",
            "sourceColumn": "PaymentID",
            "lineageTag": "70675b95-39a4-4b56-b4d3-91f4b2d9aa0e",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SalesOrderID",
            "dataType": "string",
            "sourceColumn": "SalesOrderID",
            "lineageTag": "7ce06b2b-2e6b-4a99-8bd4-1580d70f8074",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "PaymentAmount",
            "dataType": "decimal",
            "sourceColumn": "PaymentAmount",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "f34cbf07-0c53-4596-95b5-638425fd2808",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "PaymentDate",
            "dataType": "dateTime",
            "sourceColumn": "PaymentDate",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "4829376e-df0d-4e8d-9487-d28c95afdb48",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ]
          },
          {
            "name": "PaymentStatus",
            "dataType": "string",
            "sourceColumn": "PaymentStatus",
            "lineageTag": "9905616e-a56a-4f86-bf52-699dd9d31305",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FeeAmount",
            "dataType": "decimal",
            "sourceColumn": "FeeAmount",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "f7aa394c-8653-492c-919b-4a9a0cda8266",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ReconciliationDate",
            "dataType": "dateTime",
            "sourceColumn": "ReconciliationDate",
            "formatString": "Long Date",
            "lineageTag": "43a73297-41f1-411b-9f4b-d6d9f0397d6d",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "IsReconciled",
            "dataType": "boolean",
            "sourceColumn": "IsReconciled",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "370931c9-bb2c-4ff1-9849-5c23e555bdec",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DateKey",
            "formatString": "0",
            "lineageTag": "5ac6a3f7-ba74-4739-a2ae-ed539e0bdaa3",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "PaymentMethodKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PaymentMethodKey",
            "formatString": "0",
            "lineageTag": "cda34d24-f553-4cb3-aa95-a4e797a90ee6",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "PaymentKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PaymentKey",
            "formatString": "0",
            "lineageTag": "0a94ba38-43bf-4843-8f38-e98ccb31f993",
            "summarizeBy": "count",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Days Outstanding",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "IF(",
              "    FactPayment[PaymentStatus] IN {\"Pending\", \"Failed\"},",
              "    DATEDIFF(FactPayment[PaymentDate], MAX(FactPayment[PaymentDate]), DAY),",
              "    BLANK()",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "13891fbd-1e45-413a-be04-14fccf24229e",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "FactPayment",
            "mode": "import",
            "queryGroup": "9_Fact Tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = stgPayments_Combined,",
                "    #\"Removed Columns\" = Table.RemoveColumns(Source,{\"SourceFileName\"}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Removed Columns\", {\"PaymentMethod\"}, DimPaymentMethod, {\"PaymentMethod\"}, \"DimPaymentMethod\", JoinKind.LeftOuter),",
                "    #\"Expanded DimPaymentMethod\" = Table.ExpandTableColumn(#\"Merged Queries\", \"DimPaymentMethod\", {\"PaymentMethodKey\"}, {\"PaymentMethodKey\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Expanded DimPaymentMethod\",{\"PaymentID\", \"SalesOrderID\", \"PaymentAmount\", \"PaymentDate\", \"PaymentStatus\", \"PaymentMethod\", \"PaymentMethodKey\", \"FeeAmount\", \"ReconciliationDate\", \"IsReconciled\", \"LoadDateTime\"}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Reordered Columns\",{\"PaymentMethod\"}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Removed Columns1\", {\"PaymentDate\"}, DimDate, {\"Date\"}, \"DimDate\", JoinKind.LeftOuter),",
                "    #\"Expanded DimDate\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"DimDate\", {\"DateKey\"}, {\"DateKey\"}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Expanded DimDate\",{\"PaymentID\", \"SalesOrderID\", \"PaymentAmount\", \"DateKey\", \"PaymentDate\", \"PaymentMethodKey\", \"PaymentStatus\", \"FeeAmount\", \"ReconciliationDate\", \"IsReconciled\", \"LoadDateTime\"}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Reordered Columns1\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Reordered Columns2\" = Table.ReorderColumns(#\"Added Index\",{\"Index\", \"PaymentID\", \"SalesOrderID\", \"PaymentAmount\", \"DateKey\", \"PaymentDate\", \"PaymentMethodKey\", \"PaymentStatus\", \"FeeAmount\", \"ReconciliationDate\", \"IsReconciled\", \"LoadDateTime\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Reordered Columns2\",{{\"Index\", \"PaymentKey\"}}),",
                "    #\"Reordered Columns3\" = Table.ReorderColumns(#\"Renamed Columns\",{\"PaymentKey\", \"PaymentID\", \"SalesOrderID\", \"DateKey\", \"PaymentMethodKey\", \"PaymentAmount\", \"PaymentDate\", \"PaymentStatus\", \"FeeAmount\", \"ReconciliationDate\", \"IsReconciled\", \"LoadDateTime\"}),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Reordered Columns3\",{\"LoadDateTime\"})",
                "in",
                "    #\"Removed Columns2\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "FactExpense",
        "lineageTag": "ebaa2114-8053-44a1-b670-22dffed2f91b",
        "columns": [
          {
            "name": "ExpenseKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ExpenseKey",
            "formatString": "0",
            "lineageTag": "6a51cb99-5fb8-440d-82e2-82631229d89d",
            "summarizeBy": "count",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ExpenseID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ExpenseID",
            "lineageTag": "dc24be83-0ede-4c04-8e77-3646249f0674",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ExpCategoryKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ExpCategoryKey",
            "formatString": "0",
            "lineageTag": "e6b38c68-86c3-4be9-b13c-b585feddda8c",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ExpenseAmount",
            "dataType": "decimal",
            "sourceColumn": "ExpenseAmount",
            "lineageTag": "75d801e7-1be0-467c-a6b9-a07ce9aea77e",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "VendorName",
            "dataType": "string",
            "sourceColumn": "VendorName",
            "lineageTag": "3c9d5a96-7621-4ff1-831b-c612d603ad4d",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description",
            "lineageTag": "b0d1b946-6021-4ff6-af57-4eb08b4ac3e1",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DateKey",
            "formatString": "0",
            "lineageTag": "77c5648f-a30f-4555-b31e-ec8fc3e76f08",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ExpenseDate",
            "dataType": "dateTime",
            "sourceColumn": "ExpenseDate",
            "formatString": "Long Date",
            "lineageTag": "11d9f46b-e928-41b2-a245-4d7add70e825",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "FactExpense",
            "mode": "import",
            "queryGroup": "9_Fact Tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = stgExpenses,",
                "    #\"Added Index\" = Table.AddIndexColumn(Source, \"Index\", 1, 1, Int64.Type),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Index\",{\"Index\", \"ExpenseID\", \"CategoryName\", \"ExpenseAmount\", \"ExpenseDate\", \"VendorName\", \"Description\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Reordered Columns\",{{\"Index\", \"ExpenseKey\"}}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Renamed Columns\", {\"CategoryName\"}, DimExpCategory, {\"CategoryName\"}, \"DimExpCategory\", JoinKind.LeftOuter),",
                "    #\"Expanded DimExpCategory\" = Table.ExpandTableColumn(#\"Merged Queries\", \"DimExpCategory\", {\"ExpCategoryKey\"}, {\"ExpCategoryKey\"}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Expanded DimExpCategory\",{\"ExpenseKey\", \"ExpenseID\", \"CategoryName\", \"ExpCategoryKey\", \"ExpenseAmount\", \"ExpenseDate\", \"VendorName\", \"Description\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Reordered Columns1\",{\"CategoryName\"}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Removed Columns\", {\"ExpenseDate\"}, DimDate, {\"Date\"}, \"DimDate\", JoinKind.LeftOuter),",
                "    #\"Expanded DimDate\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"DimDate\", {\"DateKey\"}, {\"DateKey\"}),",
                "    #\"Reordered Columns2\" = Table.ReorderColumns(#\"Expanded DimDate\",{\"ExpenseKey\", \"ExpenseID\", \"DateKey\", \"ExpCategoryKey\", \"ExpenseAmount\", \"ExpenseDate\", \"VendorName\", \"Description\"}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Reordered Columns2\",{\"ExpenseDate\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Columns1\",{{\"ExpenseAmount\", Currency.Type}}),",
                "    #\"Merged Queries2\" = Table.NestedJoin(#\"Changed Type\", {\"DateKey\"}, DimDate, {\"DateKey\"}, \"DimDate\", JoinKind.LeftOuter),",
                "    #\"Expanded DimDate1\" = Table.ExpandTableColumn(#\"Merged Queries2\", \"DimDate\", {\"Date\"}, {\"Date\"}),",
                "    #\"Reordered Columns3\" = Table.ReorderColumns(#\"Expanded DimDate1\",{\"ExpenseKey\", \"ExpenseID\", \"DateKey\", \"Date\", \"ExpCategoryKey\", \"ExpenseAmount\", \"VendorName\", \"Description\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Reordered Columns3\",{{\"Date\", \"ExpenseDate\"}})",
                "in",
                "    #\"Renamed Columns1\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "_Measures",
        "lineageTag": "5825a39d-cc4f-4d09-b2dd-2581551019cd",
        "partitions": [
          {
            "name": "_Measures",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Removed Columns\" = Table.RemoveColumns(Source,{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Total Income",
            "expression": "SUM(FactSalesHeader[NetAmount])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "displayFolder": "BASE MEASURES",
            "lineageTag": "e2205443-520f-41c5-b97f-95f074559877"
          },
          {
            "name": "Total Expenses",
            "expression": [
              "",
              "SUM(FactExpense[ExpenseAmount])"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "displayFolder": "BASE MEASURES",
            "lineageTag": "96039ba4-2165-41ca-a428-9481f40cbe24"
          },
          {
            "name": "Net Profit",
            "expression": [
              "",
              "[Total Income] - [Total Expenses]"
            ],
            "formatString": "\"Rs\"#,0.###############;-\"Rs\"#,0.###############;\"Rs\"#,0.###############",
            "displayFolder": "BASE MEASURES",
            "lineageTag": "bc5762d1-2d6b-4506-bdb2-3a2ca6724915",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-PK\"}"
              }
            ]
          },
          {
            "name": "Profit Margin %",
            "expression": [
              "",
              "DIVIDE([Net Profit], [Total Income], 0)"
            ],
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "displayFolder": "BASE MEASURES",
            "lineageTag": "5df7ecc4-c262-4e88-b3c3-45ae9c7eead7"
          },
          {
            "name": "Payments Received",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(FactPayment[PaymentAmount]),",
              "    FactPayment[PaymentStatus] = \"Received\"",
              ")"
            ],
            "formatString": "\"Rs\"#,0.###############;-\"Rs\"#,0.###############;\"Rs\"#,0.###############",
            "displayFolder": "BASE MEASURES",
            "lineageTag": "995ecd0a-36a6-4ddc-ac91-3108d7da5269",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-PK\"}"
              }
            ]
          },
          {
            "name": "Payments Pending",
            "expression": [
              "",
              "VAR Pending = CALCULATE(SUM(FactPayment[PaymentAmount]), FactPayment[PaymentStatus] = \"Pending\")",
              "RETURN Pending "
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "displayFolder": "BASE MEASURES",
            "lineageTag": "2e94578c-58d4-4531-99b0-64cd6b19fed4"
          },
          {
            "name": "Collection Rate %",
            "expression": [
              "",
              "DIVIDE([Payments Received], [Total Income], 0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "BASE MEASURES",
            "lineageTag": "0e1de07d-32a6-448f-a1b9-cb349561ea48"
          },
          {
            "name": "Expense % of Total",
            "expression": [
              "",
              "DIVIDE(",
              "    [Total Expenses],",
              "    CALCULATE([Total Expenses], REMOVEFILTERS(DimExpCategory)),",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "BREAKDOWN MEASURES",
            "lineageTag": "c875bdf3-5705-4cfc-b105-fad4b25b7551"
          },
          {
            "name": "Expense % of Revenue",
            "expression": [
              "",
              "DIVIDE([Total Expenses], [Total Income], 0)",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "BREAKDOWN MEASURES",
            "lineageTag": "d641de40-c502-443d-84da-7f31a45c8b5d"
          },
          {
            "name": "Payment Method % of Total",
            "expression": [
              "",
              "DIVIDE(",
              "    [Total Income],",
              "    CALCULATE([Total Income], REMOVEFILTERS(DimPaymentMethod)),",
              "    0",
              ")"
            ],
            "displayFolder": "BREAKDOWN MEASURES",
            "lineageTag": "ecb54ac6-a793-4988-8444-f1fbb4ac159a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Payment Fees Total",
            "expression": [
              "",
              "SUM(FactPayment[FeeAmount])"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "displayFolder": "BREAKDOWN MEASURES",
            "lineageTag": "65540dbe-3df2-4806-b37c-fd2474a8bc19"
          },
          {
            "name": "Payment Fees % of Revenue",
            "expression": [
              "",
              "DIVIDE([Payment Fees Total], [Total Income], 0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "BREAKDOWN MEASURES",
            "lineageTag": "20b9b485-c662-4685-8014-cdc871c5200c"
          },
          {
            "name": "Cash Flow",
            "expression": [
              "",
              "[Total Income] - [Total Expenses]"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "displayFolder": "BASE MEASURES",
            "lineageTag": "2a928617-82b9-48c2-98a9-b26705ad67e2"
          },
          {
            "name": "MoM Revenue",
            "expression": [
              "",
              "VAR MAXDATE = MAX(FactSalesHeader[OrderDate])           -- Last sale date",
              "VAR ST_CURR = EOMONTH(MAXDATE, -1) + 1                 -- Start of current month",
              "VAR END_CURR = MAXDATE                                  -- End of current month",
              "VAR ST_PREV = EOMONTH(MAXDATE, -2) + 1                 -- Start of previous month",
              "VAR END_PREV = EOMONTH(MAXDATE, -1)                    -- End of previous month",
              "",
              "-- Current Month Revenue",
              "VAR CURR_MONTH =",
              "    CALCULATE(",
              "        SUM(FactSalesHeader[NetAmount]),",
              "        DATESBETWEEN('DimDate'[Date], ST_CURR, END_CURR)",
              "    )",
              "",
              "-- Previous Month Revenue",
              "VAR PREV_MONTH =",
              "    CALCULATE(",
              "        SUM(FactSalesHeader[NetAmount]),",
              "        DATESBETWEEN('DimDate'[Date], ST_PREV, END_PREV)",
              "    )",
              "",
              "-- Absolute change",
              "VAR _change = CURR_MONTH - PREV_MONTH",
              "",
              "-- Percent change",
              "VAR _pctchange = DIVIDE(_change, PREV_MONTH, 0)",
              "",
              "-- Formatted output",
              "VAR _Condition =",
              "    IF(",
              "        ISBLANK(PREV_MONTH),",
              "        \"No previous month data\",",
              "        IF(",
              "            _pctchange > 0,",
              "            UNICHAR(129029) & FORMAT(_pctchange, \"0.0%\") & \" (\" & FORMAT(_change, \"+$#,###;-$#,###\") & \" MoM)\",",
              "            UNICHAR(129031) & FORMAT(_pctchange, \"0.0%\") & \" (\" & FORMAT(_change, \"+$#,###;-$#,###\") & \" MoM)\"",
              "        )",
              "    )",
              "",
              "RETURN",
              "    _Condition"
            ],
            "displayFolder": "TIMESERIES",
            "lineageTag": "9e327498-1294-4b25-b75a-85d93a299f14"
          },
          {
            "name": "YoY Revenue",
            "expression": [
              "",
              "VAR LASTSALE = MAX(FactSalesHeader[OrderDate])          -- Last actual sale date",
              "VAR CURR_YEAR = YEAR(LASTSALE)",
              "VAR PREV_YEAR = CURR_YEAR - 1",
              "",
              "-- Current Year YTD (from Jan 1 to last sale date)",
              "VAR CY_YTD =",
              "    CALCULATE(",
              "        SUM(FactSalesHeader[NetAmount]),",
              "        DATESBETWEEN(",
              "            'DimDate'[Date],",
              "            DATE(CURR_YEAR, 1, 1),",
              "            LASTSALE",
              "        )",
              "    )",
              "",
              "-- Previous Year YTD (same period last year)",
              "VAR PY_YTD =",
              "    CALCULATE(",
              "        SUM(FactSalesHeader[NetAmount]),",
              "        DATESBETWEEN(",
              "            'DimDate'[Date],",
              "            DATE(PREV_YEAR, 1, 1),",
              "            DATE(PREV_YEAR, MONTH(LASTSALE), DAY(LASTSALE))",
              "        )",
              "    )",
              "",
              "-- Absolute change YoY",
              "VAR _change = CY_YTD - PY_YTD",
              "",
              "-- Percent change YoY",
              "VAR _pctchange = DIVIDE(_change, PY_YTD, 0)",
              "",
              "-- Formatted text for arrows, % and absolute change",
              "VAR _Condition =",
              "    IF(",
              "        ISBLANK(PY_YTD),",
              "        \"No previous year data\",",
              "        IF(",
              "            _pctchange > 0,",
              "            UNICHAR(129029) & FORMAT(_pctchange, \"0.0%\") & \" (\" & FORMAT(_change, \"+$#,###;-$#,###\") & \" YoY)\",",
              "            UNICHAR(129031) & FORMAT(_pctchange, \"0.0%\") & \" (\" & FORMAT(_change, \"+$#,###;-$#,###\") & \" YoY)\"",
              "        )",
              "    )",
              "",
              "RETURN",
              "    _Condition"
            ],
            "displayFolder": "TIMESERIES",
            "lineageTag": "6fa86bf4-8298-473c-ae8d-b1e67d4745e4"
          },
          {
            "name": "MoM Revenue Color",
            "expression": [
              "",
              "VAR MAXDATE = MAX(FactSalesHeader[OrderDate])           -- Last sale date",
              "VAR ST_CURR = EOMONTH(MAXDATE, -1) + 1                 -- Start of current month",
              "VAR END_CURR = MAXDATE                                  -- End of current month",
              "VAR ST_PREV = EOMONTH(MAXDATE, -2) + 1                 -- Start of previous month",
              "VAR END_PREV = EOMONTH(MAXDATE, -1)                    -- End of previous month",
              "",
              "-- Current Month Revenue",
              "VAR CURR_MONTH =",
              "    CALCULATE(",
              "        SUM(FactSalesHeader[NetAmount]),",
              "        DATESBETWEEN('DimDate'[Date], ST_CURR, END_CURR)",
              "    )",
              "",
              "-- Previous Month Revenue",
              "VAR PREV_MONTH =",
              "    CALCULATE(",
              "        SUM(FactSalesHeader[NetAmount]),",
              "        DATESBETWEEN('DimDate'[Date], ST_PREV, END_PREV)",
              "    )",
              "",
              "-- MoM percent change",
              "VAR _pctchange = DIVIDE(CURR_MONTH - PREV_MONTH, PREV_MONTH, 0)",
              "",
              "-- Assign color",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(PREV_MONTH), \"#808080\",      -- Gray if no previous month data",
              "    _pctchange > 0, \"#008000\",           -- Green if positive growth",
              "    _pctchange < 0, \"#FF0000\",           -- Red if decline",
              "    \"#000000\"                             -- Black if zero change",
              ")"
            ],
            "displayFolder": "TIMESERIES",
            "lineageTag": "d396af88-8ebd-40b3-b9c4-23305662bde9"
          },
          {
            "name": "CF Bars",
            "expression": [
              "",
              "VAR _table =",
              "    SUMMARIZE(",
              "        ALLSELECTED('DimDate'),",
              "        'DimDate'[MonthShort],",
              "        \"IncomeValue\", [Total Income]",
              "    )",
              "VAR _maxval = MAXX(_table, [IncomeValue])",
              "VAR _minval = MINX(_table, [IncomeValue])",
              "VAR _currval = [Total Income]",
              "",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    _currval = _maxval, \"Green\",",
              "    _currval = _minval, \"Red\",",
              "    \"Light Grey\"",
              ")"
            ],
            "displayFolder": "TIMESERIES",
            "lineageTag": "dbcbcab0-2b3c-4479-a622-61a7db1ebe37"
          },
          {
            "name": "CF Bars Expense",
            "expression": [
              "",
              "VAR _table =",
              "    SUMMARIZE(",
              "        ALLSELECTED('DimDate'),",
              "        'DimDate'[MonthShort],",
              "        \"ExpenseValue\", [Total Expenses]",
              "    )",
              "VAR _maxval = MAXX(_table, [ExpenseValue])",
              "VAR _minval = MINX(_table, [ExpenseValue])",
              "VAR _currval = [Total Expenses]   -- Use Expenses, not Income",
              "",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    _currval = _maxval, \"Red\",         -- Max Expense → Red",
              "    _currval = _minval, \"Green\",       -- Min Expense → Green",
              "    \"Light Grey\"",
              ")"
            ],
            "displayFolder": "TIMESERIES",
            "lineageTag": "c175b337-02fe-4253-ad1f-035553a175ca"
          },
          {
            "name": "MoM Expenses",
            "expression": [
              "",
              "VAR MAXDATE = MAX(FactExpense[ExpenseDate])           -- Last expense date",
              "VAR ST_CURR = EOMONTH(MAXDATE, -1) + 1               -- Start of current month",
              "VAR END_CURR = MAXDATE                                -- End of current month",
              "VAR ST_PREV = EOMONTH(MAXDATE, -2) + 1               -- Start of previous month",
              "VAR END_PREV = EOMONTH(MAXDATE, -1)                  -- End of previous month",
              "",
              "-- Current Month Expenses",
              "VAR CURR_MONTH =",
              "    CALCULATE(",
              "        SUM(FactExpense[ExpenseAmount]),",
              "        DATESBETWEEN('DimDate'[Date], ST_CURR, END_CURR)",
              "    )",
              "",
              "-- Previous Month Expenses",
              "VAR PREV_MONTH =",
              "    CALCULATE(",
              "        SUM(FactExpense[ExpenseAmount]),",
              "        DATESBETWEEN('DimDate'[Date], ST_PREV, END_PREV)",
              "    )",
              "",
              "-- Absolute change",
              "VAR _change = CURR_MONTH - PREV_MONTH",
              "",
              "-- Percent change",
              "VAR _pctchange = DIVIDE(_change, PREV_MONTH, 0)",
              "",
              "-- Formatted output",
              "VAR _Condition =",
              "    IF(",
              "        ISBLANK(PREV_MONTH),",
              "        \"No previous month data\",",
              "        IF(",
              "            _pctchange > 0,",
              "            UNICHAR(129031) & FORMAT(_pctchange, \"0.0%\") & \" (\" & FORMAT(_change, \"-$#,###;+$#,###\") & \" MoM)\",  -- Up arrow for increase in Expense",
              "            UNICHAR(129029) & FORMAT(_pctchange, \"0.0%\") & \" (\" & FORMAT(_change, \"-$#,###;+$#,###\") & \" MoM)\"   -- Down arrow for decrease",
              "        )",
              "    )",
              "",
              "RETURN",
              "    _Condition"
            ],
            "displayFolder": "TIMESERIES",
            "lineageTag": "fc4357fd-9f35-4ef1-b15e-bc02e0874f71"
          },
          {
            "name": "YoY Expenses",
            "expression": [
              "",
              "VAR LASTSALE = MAX(FactExpense[ExpenseDate])          -- Last actual expense date",
              "VAR CURR_YEAR = YEAR(LASTSALE)",
              "VAR PREV_YEAR = CURR_YEAR - 1",
              "",
              "-- Current Year YTD Expenses (Jan 1 to last expense date)",
              "VAR CY_YTD =",
              "    CALCULATE(",
              "        SUM(FactExpense[ExpenseAmount]),",
              "        DATESBETWEEN(",
              "            'DimDate'[Date],",
              "            DATE(CURR_YEAR, 1, 1),",
              "            LASTSALE",
              "        )",
              "    )",
              "",
              "-- Previous Year YTD Expenses (same period last year)",
              "VAR PY_YTD =",
              "    CALCULATE(",
              "        SUM(FactExpense[ExpenseAmount]),",
              "        DATESBETWEEN(",
              "            'DimDate'[Date],",
              "            DATE(PREV_YEAR, 1, 1),",
              "            DATE(PREV_YEAR, MONTH(LASTSALE), DAY(LASTSALE))",
              "        )",
              "    )",
              "",
              "-- Absolute change YoY",
              "VAR _change = CY_YTD - PY_YTD",
              "",
              "-- Percent change YoY",
              "VAR _pctchange = DIVIDE(_change, PY_YTD, 0)",
              "",
              "-- Formatted output with arrows",
              "VAR _Condition =",
              "    IF(",
              "        ISBLANK(PY_YTD),",
              "        \"No previous year data\",",
              "        IF(",
              "            _pctchange > 0,",
              "            UNICHAR(129031) & FORMAT(_pctchange, \"0.0%\") & \" (\" & FORMAT(_change, \"-$#,###;+$#,###\") & \" YoY)\",   -- Up arrow for decrease = good",
              "            UNICHAR(129029) & FORMAT(_pctchange, \"0.0%\") & \" (\" & FORMAT(_change, \"-$#,###;+$#,###\") & \" YoY)\"    -- Down arrow for increase = bad",
              "        )",
              "    )",
              "",
              "RETURN",
              "    _Condition"
            ],
            "displayFolder": "TIMESERIES",
            "lineageTag": "2ad164cc-d722-406b-8944-9b481809739d"
          },
          {
            "name": "MoM Cash Flow",
            "expression": [
              "",
              "VAR MAXDATE = MAX(FactSalesHeader[OrderDate])           -- Last sale date (also used for Cash Flow)",
              "VAR ST_CURR = EOMONTH(MAXDATE, -1) + 1                 -- Start of current month",
              "VAR END_CURR = MAXDATE                                  -- End of current month",
              "VAR ST_PREV = EOMONTH(MAXDATE, -2) + 1                 -- Start of previous month",
              "VAR END_PREV = EOMONTH(MAXDATE, -1)                    -- End of previous month",
              "",
              "-- Current Month Cash Flow",
              "VAR CURR_MONTH =",
              "    CALCULATE(",
              "        [Total Income] - [Total Expenses],",
              "        DATESBETWEEN('DimDate'[Date], ST_CURR, END_CURR)",
              "    )",
              "",
              "-- Previous Month Cash Flow",
              "VAR PREV_MONTH =",
              "    CALCULATE(",
              "        [Total Income] - [Total Expenses],",
              "        DATESBETWEEN('DimDate'[Date], ST_PREV, END_PREV)",
              "    )",
              "",
              "-- Absolute change",
              "VAR _change = CURR_MONTH - PREV_MONTH",
              "",
              "-- Percent change",
              "VAR _pctchange = DIVIDE(_change, PREV_MONTH, 0)",
              "",
              "-- Formatted output",
              "VAR _Condition =",
              "    IF(",
              "        ISBLANK(PREV_MONTH),",
              "        \"No previous month data\",",
              "        IF(",
              "            _pctchange > 0,",
              "            UNICHAR(129029) & FORMAT(_pctchange, \"0.0%\") & \" (\" & FORMAT(_change, \"+$#,###;-$#,###\") & \" MoM)\",  -- Positive CF growth",
              "            UNICHAR(129031) & FORMAT(_pctchange, \"0.0%\") & \" (\" & FORMAT(_change, \"+$#,###;-$#,###\") & \" MoM)\"   -- Negative CF growth",
              "        )",
              "    )",
              "",
              "RETURN",
              "    _Condition"
            ],
            "displayFolder": "TIMESERIES",
            "lineageTag": "80d642b8-b27a-4cd6-9b7c-f510cf9e61a8"
          },
          {
            "name": "YoY Cash Flow",
            "expression": [
              "",
              "VAR LASTSALE = MAX(FactSalesHeader[OrderDate])         -- Last actual date",
              "VAR CURR_YEAR = YEAR(LASTSALE)",
              "VAR PREV_YEAR = CURR_YEAR - 1",
              "",
              "-- Current Year YTD Cash Flow",
              "VAR CY_YTD =",
              "    CALCULATE(",
              "        [Total Income] - [Total Expenses],",
              "        DATESBETWEEN(",
              "            'DimDate'[Date],",
              "            DATE(CURR_YEAR, 1, 1),",
              "            LASTSALE",
              "        )",
              "    )",
              "",
              "-- Previous Year YTD Cash Flow",
              "VAR PY_YTD =",
              "    CALCULATE(",
              "        [Total Income] - [Total Expenses],",
              "        DATESBETWEEN(",
              "            'DimDate'[Date],",
              "            DATE(PREV_YEAR, 1, 1),",
              "            DATE(PREV_YEAR, MONTH(LASTSALE), DAY(LASTSALE))",
              "        )",
              "    )",
              "",
              "-- Absolute change",
              "VAR _change = CY_YTD - PY_YTD",
              "",
              "-- Percent change",
              "VAR _pctchange = DIVIDE(_change, PY_YTD, 0)",
              "",
              "-- Formatted text with arrows",
              "VAR _Condition =",
              "    IF(",
              "        ISBLANK(PY_YTD),",
              "        \"No previous year data\",",
              "        IF(",
              "            _pctchange > 0,",
              "            UNICHAR(129029) & \" \" & FORMAT(_pctchange, \"0.0%\") &",
              "            \" (\" & FORMAT(_change, \"+$#,###;-$#,###\") & \" YoY)\",",
              "            UNICHAR(129031) & \" \" & FORMAT(_pctchange, \"0.0%\") &",
              "            \" (\" & FORMAT(_change, \"+$#,###;-$#,###\") & \" YoY)\"",
              "        )",
              "    )",
              "",
              "RETURN",
              "    _Condition",
              ""
            ],
            "displayFolder": "TIMESERIES",
            "lineageTag": "e3901360-99df-4188-bdbd-59e0cfff1712"
          },
          {
            "name": "YoY Revenue Color",
            "expression": [
              "",
              "VAR LASTSALE = MAX(FactSalesHeader[OrderDate])",
              "VAR CURR_YEAR = YEAR(LASTSALE)",
              "VAR PREV_YEAR = CURR_YEAR - 1",
              "",
              "-- Current Year YTD",
              "VAR CY_YTD =",
              "    CALCULATE(",
              "        SUM(FactSalesHeader[NetAmount]),",
              "        DATESBETWEEN(",
              "            'DimDate'[Date],",
              "            DATE(CURR_YEAR, 1, 1),",
              "            LASTSALE",
              "        )",
              "    )",
              "",
              "-- Previous Year YTD",
              "VAR PY_YTD =",
              "    CALCULATE(",
              "        SUM(FactSalesHeader[NetAmount]),",
              "        DATESBETWEEN(",
              "            'DimDate'[Date],",
              "            DATE(PREV_YEAR, 1, 1),",
              "            DATE(PREV_YEAR, MONTH(LASTSALE), DAY(LASTSALE))",
              "        )",
              "    )",
              "",
              "-- Percent Change",
              "VAR _pctchange = DIVIDE(CY_YTD - PY_YTD, PY_YTD, 0)",
              "",
              "-- Assign color based on value",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(PY_YTD), \"#808080\",         -- Gray if no previous data",
              "    _pctchange > 0, \"#008000\",           -- Green if growth",
              "    _pctchange < 0, \"#FF0000\",           -- Red if negative",
              "    \"#000000\"                             -- Black if zero change",
              ")"
            ],
            "displayFolder": "TIMESERIES",
            "lineageTag": "c7aac78e-14dc-40d2-925a-b46656d0c3cf"
          },
          {
            "name": "YoY Expense Color",
            "expression": [
              "",
              "VAR LASTSALE = MAX(FactExpense[ExpenseDate])",
              "VAR CURR_YEAR = YEAR(LASTSALE)",
              "VAR PREV_YEAR = CURR_YEAR - 1",
              "",
              "-- Current Year YTD",
              "VAR CY_YTD =",
              "    CALCULATE(",
              "        SUM(FactExpense[ExpenseDate]),",
              "        DATESBETWEEN(",
              "            'DimDate'[Date],",
              "            DATE(CURR_YEAR, 1, 1),",
              "            LASTSALE",
              "        )",
              "    )",
              "",
              "-- Previous Year YTD",
              "VAR PY_YTD =",
              "    CALCULATE(",
              "        SUM(FactExpense[ExpenseDate]),",
              "        DATESBETWEEN(",
              "            'DimDate'[Date],",
              "            DATE(PREV_YEAR, 1, 1),",
              "            DATE(PREV_YEAR, MONTH(LASTSALE), DAY(LASTSALE))",
              "        )",
              "    )",
              "",
              "-- Percent Change",
              "VAR _pctchange = DIVIDE(CY_YTD - PY_YTD, PY_YTD, 0)",
              "",
              "-- Assign color based on value",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(PY_YTD), \"#808080\",         -- Gray if no previous data",
              "    _pctchange > 0, \"#008000\",           -- Green if growth",
              "    _pctchange < 0, \"#FF0000\",           -- Red if negative",
              "    \"#000000\"                             -- Black if zero change",
              ")"
            ],
            "displayFolder": "TIMESERIES",
            "lineageTag": "b3c2b3a1-7f80-4ad2-b43a-c8fabf1eab09"
          },
          {
            "name": "YoY Cash Flow Color",
            "expression": [
              "",
              "VAR LASTSALE = MAX(FactSalesHeader[OrderDate])",
              "VAR CURR_YEAR = YEAR(LASTSALE)",
              "VAR PREV_YEAR = CURR_YEAR - 1",
              "",
              "-- Current Year YTD Cash Flow",
              "VAR CY_YTD =",
              "    CALCULATE(",
              "        [Total Income] - [Total Expenses],",
              "        DATESBETWEEN(",
              "            'DimDate'[Date],",
              "            DATE(CURR_YEAR, 1, 1),",
              "            LASTSALE",
              "        )",
              "    )",
              "",
              "-- Previous Year YTD Cash Flow",
              "VAR PY_YTD =",
              "    CALCULATE(",
              "        [Total Income] - [Total Expenses],",
              "        DATESBETWEEN(",
              "            'DimDate'[Date],",
              "            DATE(PREV_YEAR, 1, 1),",
              "            DATE(PREV_YEAR, MONTH(LASTSALE), DAY(LASTSALE))",
              "        )",
              "    )",
              "",
              "-- Percent change",
              "VAR _pctchange = DIVIDE(CY_YTD - PY_YTD, PY_YTD, 0)",
              "",
              "-- Assign color",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(PY_YTD), \"#808080\",     -- Gray if no previous data",
              "    _pctchange > 0, \"#008000\",      -- Green if positive cash flow growth",
              "    _pctchange < 0, \"#FF0000\",      -- Red if decline",
              "    \"#000000\"                        -- Black if no change",
              ")"
            ],
            "displayFolder": "TIMESERIES",
            "lineageTag": "6ebd6aaa-065b-47f2-861d-f6b3cfe6fe49"
          },
          {
            "name": "MoM Profit Margin %",
            "expression": [
              "",
              "VAR MAXDATE = MAX(FactSalesHeader[OrderDate])           -- Last sale date",
              "VAR ST_CURR = EOMONTH(MAXDATE, -1) + 1                 -- Start of current month",
              "VAR END_CURR = MAXDATE                                  -- End of current month",
              "VAR ST_PREV = EOMONTH(MAXDATE, -2) + 1                 -- Start of previous month",
              "VAR END_PREV = EOMONTH(MAXDATE, -1)                    -- End of previous month",
              "",
              "-- Current Month Profit Margin",
              "VAR CURR_PM =",
              "    CALCULATE(",
              "        DIVIDE([Net Profit], [Total Income], 0),",
              "        DATESBETWEEN('DimDate'[Date], ST_CURR, END_CURR)",
              "    )",
              "",
              "-- Previous Month Profit Margin",
              "VAR PREV_PM =",
              "    CALCULATE(",
              "        DIVIDE([Net Profit], [Total Income], 0),",
              "        DATESBETWEEN('DimDate'[Date], ST_PREV, END_PREV)",
              "    )",
              "",
              "-- Absolute change",
              "VAR _change = CURR_PM - PREV_PM",
              "",
              "-- Percent change",
              "VAR _pctchange = DIVIDE(_change, PREV_PM, 0)",
              "",
              "-- Formatted output with arrows",
              "VAR _Condition =",
              "    IF(",
              "        ISBLANK(PREV_PM),",
              "        \"No previous month data\",",
              "        IF(",
              "            _pctchange > 0,",
              "            UNICHAR(129029) & \" \" & FORMAT(CURR_PM, \"0.0%\") &",
              "            \" (\" & FORMAT(_pctchange, \"0.0%\") & \" MoM)\",",
              "            UNICHAR(129031) & \" \" & FORMAT(CURR_PM, \"0.0%\") &",
              "            \" (\" & FORMAT(_pctchange, \"0.0%\") & \" MoM)\"",
              "        )",
              "    )",
              "",
              "RETURN",
              "    _Condition"
            ],
            "displayFolder": "TIMESERIES",
            "lineageTag": "495b408f-217d-4b95-8657-0b511f69aed4"
          },
          {
            "name": "YoY Profit Margin %",
            "expression": [
              "",
              "VAR LASTSALE = MAX(FactSalesHeader[OrderDate])",
              "VAR CURR_YEAR = YEAR(LASTSALE)",
              "VAR PREV_YEAR = CURR_YEAR - 1",
              "",
              "-- Current Year YTD Profit Margin",
              "VAR CY_PM =",
              "    CALCULATE(",
              "        DIVIDE([Net Profit], [Total Income], 0),",
              "        DATESBETWEEN('DimDate'[Date], DATE(CURR_YEAR, 1, 1), LASTSALE)",
              "    )",
              "",
              "-- Previous Year YTD Profit Margin",
              "VAR PY_PM =",
              "    CALCULATE(",
              "        DIVIDE([Net Profit], [Total Income], 0),",
              "        DATESBETWEEN('DimDate'[Date], DATE(PREV_YEAR, 1, 1), DATE(PREV_YEAR, MONTH(LASTSALE), DAY(LASTSALE)))",
              "    )",
              "",
              "-- Absolute change",
              "VAR _change = CY_PM - PY_PM",
              "",
              "-- Percent change",
              "VAR _pctchange = DIVIDE(_change, PY_PM, 0)",
              "",
              "-- Formatted output with arrows",
              "VAR _Condition =",
              "    IF(",
              "        ISBLANK(PY_PM),",
              "        \"No previous year data\",",
              "        IF(",
              "            _pctchange > 0,",
              "            UNICHAR(129029) & \" \" & FORMAT(CY_PM, \"0.0%\") &",
              "            \" (\" & FORMAT(_pctchange, \"0.0%\") & \" YoY)\",",
              "            UNICHAR(129031) & \" \" & FORMAT(CY_PM, \"0.0%\") &",
              "            \" (\" & FORMAT(_pctchange, \"0.0%\") & \" YoY)\"",
              "        )",
              "    )",
              "",
              "RETURN",
              "    _Condition"
            ],
            "displayFolder": "TIMESERIES",
            "lineageTag": "c237fc27-6447-4199-b544-7167cc30555b"
          },
          {
            "name": "MoM Collection Rate %",
            "expression": [
              "",
              "VAR MAXDATE = MAX(FactPayment[PaymentDate])           -- Last payment date",
              "VAR ST_CURR = EOMONTH(MAXDATE, -1) + 1               -- Start of current month",
              "VAR END_CURR = MAXDATE                                -- End of current month",
              "VAR ST_PREV = EOMONTH(MAXDATE, -2) + 1               -- Start of previous month",
              "VAR END_PREV = EOMONTH(MAXDATE, -1)                  -- End of previous month",
              "",
              "-- Current Month Collection Rate",
              "VAR CURR_RATE =",
              "    CALCULATE(",
              "        DIVIDE([Payments Received], [Total Income], 0),",
              "        DATESBETWEEN('DimDate'[Date], ST_CURR, END_CURR)",
              "    )",
              "",
              "-- Previous Month Collection Rate",
              "VAR PREV_RATE =",
              "    CALCULATE(",
              "        DIVIDE([Payments Received], [Total Income], 0),",
              "        DATESBETWEEN('DimDate'[Date], ST_PREV, END_PREV)",
              "    )",
              "",
              "-- Absolute change",
              "VAR _change = CURR_RATE - PREV_RATE",
              "",
              "-- Percent change",
              "VAR _pctchange = DIVIDE(_change, PREV_RATE, 0)",
              "",
              "-- Formatted output with arrows",
              "VAR _Condition =",
              "    IF(",
              "        ISBLANK(PREV_RATE),",
              "        \"No previous month data\",",
              "        IF(",
              "            _pctchange > 0,",
              "            UNICHAR(129029) & \" \" & FORMAT(CURR_RATE, \"0.0%\") &",
              "            \" (\" & FORMAT(_pctchange, \"0.0%\") & \" MoM)\",",
              "            UNICHAR(129031) & \" \" & FORMAT(CURR_RATE, \"0.0%\") &",
              "            \" (\" & FORMAT(_pctchange, \"0.0%\") & \" MoM)\"",
              "        )",
              "    )",
              "",
              "RETURN",
              "    _Condition"
            ],
            "displayFolder": "TIMESERIES",
            "lineageTag": "56a0802d-8f6f-4c30-8de8-5f4148a3861d"
          },
          {
            "name": "YoY Collection Rate %",
            "expression": [
              "",
              "VAR LASTSALE = MAX(FactPayment[PaymentDate])        -- Last payment date",
              "VAR CURR_YEAR = YEAR(LASTSALE)",
              "VAR PREV_YEAR = CURR_YEAR - 1",
              "",
              "-- Current Year YTD Collection Rate",
              "VAR CY_RATE =",
              "    CALCULATE(",
              "        DIVIDE([Payments Received], [Total Income], 0),",
              "        DATESBETWEEN('DimDate'[Date], DATE(CURR_YEAR, 1, 1), LASTSALE)",
              "    )",
              "",
              "-- Previous Year YTD Collection Rate",
              "VAR PY_RATE =",
              "    CALCULATE(",
              "        DIVIDE([Payments Received], [Total Income], 0),",
              "        DATESBETWEEN('DimDate'[Date], DATE(PREV_YEAR, 1, 1), DATE(PREV_YEAR, MONTH(LASTSALE), DAY(LASTSALE)))",
              "    )",
              "",
              "-- Absolute change",
              "VAR _change = CY_RATE - PY_RATE",
              "",
              "-- Percent change",
              "VAR _pctchange = DIVIDE(_change, PY_RATE, 0)",
              "",
              "-- Formatted output with arrows",
              "VAR _Condition =",
              "    IF(",
              "        ISBLANK(PY_RATE),",
              "        \"No previous year data\",",
              "        IF(",
              "            _pctchange > 0,",
              "            UNICHAR(129029) & \" \" & FORMAT(CY_RATE, \"0.0%\") &",
              "            \" (\" & FORMAT(_pctchange, \"0.0%\") & \" YoY)\",",
              "            UNICHAR(129031) & \" \" & FORMAT(CY_RATE, \"0.0%\") &",
              "            \" (\" & FORMAT(_pctchange, \"0.0%\") & \" YoY)\"",
              "        )",
              "    )",
              "",
              "RETURN",
              "    _Condition"
            ],
            "displayFolder": "TIMESERIES",
            "lineageTag": "77b5875b-7cfc-432f-95ce-d50fe8e6a957"
          },
          {
            "name": "MoM Collection Rate Color",
            "expression": [
              "",
              "VAR MAXDATE = MAX(FactPayment[PaymentDate])",
              "VAR ST_CURR = EOMONTH(MAXDATE, -1) + 1",
              "VAR END_CURR = MAXDATE",
              "VAR ST_PREV = EOMONTH(MAXDATE, -2) + 1",
              "VAR END_PREV = EOMONTH(MAXDATE, -1)",
              "",
              "-- Current Month Collection Rate",
              "VAR CURR =",
              "    CALCULATE(",
              "        DIVIDE([Payments Received], [Total Income], 0),",
              "        DATESBETWEEN('DimDate'[Date], ST_CURR, END_CURR)",
              "    )",
              "",
              "-- Previous Month Collection Rate",
              "VAR PREV =",
              "    CALCULATE(",
              "        DIVIDE([Payments Received], [Total Income], 0),",
              "        DATESBETWEEN('DimDate'[Date], ST_PREV, END_PREV)",
              "    )",
              "",
              "VAR _pctchange = DIVIDE(CURR - PREV, PREV, 0)",
              "",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(PREV), \"#808080\",       -- No previous data",
              "    _pctchange > 0, \"#008000\",      -- Improved",
              "    _pctchange < 0, \"#FF0000\",      -- Declined",
              "    \"#000000\"                       -- No change",
              ")"
            ],
            "displayFolder": "TIMESERIES",
            "lineageTag": "46ed3faf-01a4-46b6-852e-2a770da234a7"
          },
          {
            "name": "Color YTD Collection Rate",
            "expression": [
              "",
              "VAR MaxDate =",
              "    MAX ( FactPayment[PaymentDate] )",
              "VAR CY =",
              "    YEAR ( MaxDate )",
              "VAR PY =",
              "    CY - 1",
              "VAR CURR =",
              "    CALCULATE (",
              "        DIVIDE ( [Payments Received], [Total Income], 0 ),",
              "        DATESBETWEEN ( 'DimDate'[Date], DATE ( CY, 1, 1 ), MaxDate )",
              "    )",
              "VAR PREV =",
              "    CALCULATE (",
              "        DIVIDE ( [Payments Received], [Total Income], 0 ),",
              "        DATESBETWEEN (",
              "            'DimDate'[Date],",
              "            DATE ( PY, 1, 1 ),",
              "            DATE ( PY, MONTH ( MaxDate ), DAY ( MaxDate ) )",
              "        )",
              "    )",
              "VAR _pctchange =",
              "    DIVIDE ( CURR - PREV, PREV, 0 )",
              "RETURN",
              "    SWITCH (",
              "        TRUE (),",
              "        ISBLANK ( PREV ), \"#808080\",",
              "        _pctchange > 0, \"#008000\",",
              "        _pctchange < 0, \"#FF0000\",",
              "        \"#000000\"",
              "    )"
            ],
            "displayFolder": "TIMESERIES",
            "lineageTag": "6a75fd97-ff19-489c-bf3e-c1d513d403b8"
          },
          {
            "name": "MoM Expense Color",
            "expression": [
              "",
              "VAR LASTEXP = MAX(FactExpense[ExpenseDate])",
              "",
              "-- Current Month Start & End",
              "VAR CM_START = DATE(YEAR(LASTEXP), MONTH(LASTEXP), 1)",
              "VAR CM_END   = LASTEXP",
              "",
              "-- Previous Month Start & End",
              "VAR PM_START = DATE(YEAR(LASTEXP), MONTH(LASTEXP) - 1, 1)",
              "VAR PM_END   = EOMONTH(LASTEXP, -1)",
              "",
              "-- Current Month Expense",
              "VAR CM =",
              "    CALCULATE(",
              "        SUM(FactExpense[ExpenseAmount]),",
              "        DATESBETWEEN('DimDate'[Date], CM_START, CM_END)",
              "    )",
              "",
              "-- Previous Month Expense",
              "VAR PM =",
              "    CALCULATE(",
              "        SUM(FactExpense[ExpenseAmount]),",
              "        DATESBETWEEN('DimDate'[Date], PM_START, PM_END)",
              "    )",
              "",
              "-- Percent Change",
              "VAR _pctchange = DIVIDE(CM - PM, PM, 0)",
              "",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(PM), \"#808080\",     -- Gray if no previous month",
              "    _pctchange > 0, \"#008000\",  -- Green if increased",
              "    _pctchange < 0, \"#FF0000\",  -- Red if decreased",
              "    \"#000000\"                   -- Black if no change",
              ")"
            ],
            "displayFolder": "TIMESERIES",
            "lineageTag": "a6a54a94-31b9-4ba3-b1b8-f1ade195aa5a"
          },
          {
            "name": "Previous Year Revenue",
            "expression": [
              "",
              "VAR LASTSALE =",
              "    MAX(FactSalesHeader[OrderDate])",
              "",
              "VAR CURR_YEAR =",
              "    YEAR(LASTSALE)",
              "",
              "VAR PREV_YEAR =",
              "    CURR_YEAR - 1",
              "",
              "VAR PREV_START =",
              "    DATE(PREV_YEAR, 1, 1)",
              "",
              "VAR PREV_END =",
              "    DATE(PREV_YEAR, 12, 31)",
              "",
              "RETURN",
              "CALCULATE(",
              "    SUM(FactSalesHeader[NetAmount]),",
              "    DATESBETWEEN(",
              "        'DimDate'[Date],",
              "        PREV_START,",
              "        PREV_END",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "displayFolder": "TIMESERIES",
            "lineageTag": "8d96c6fa-651b-48f2-a31e-9b1eacd847a2"
          },
          {
            "name": "Waterfall - Expected",
            "expression": "[Total Income]",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "displayFolder": "BREAKDOWN MEASURES",
            "lineageTag": "b303fade-30ed-4807-a5ae-5786e792ae61"
          },
          {
            "name": "Waterfall - Received",
            "expression": "[Payments Received]",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "displayFolder": "BREAKDOWN MEASURES",
            "lineageTag": "4be73174-b1c1-4aa9-8a37-656ff97b2d17"
          },
          {
            "name": "Waterfall - Pending",
            "expression": "-[Payments Pending]",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "displayFolder": "BREAKDOWN MEASURES",
            "lineageTag": "bcea094a-964b-4491-874d-233994aea776"
          },
          {
            "name": "Payments Failed",
            "expression": [
              "",
              "VAR Failed = CALCULATE(SUM(FactPayment[PaymentAmount]), FactPayment[PaymentStatus] = \"Failed\")",
              "RETURN",
              "Failed"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "displayFolder": "TIMESERIES",
            "lineageTag": "5f2fefef-7f5c-4f03-9d4a-0fd58c212f13"
          },
          {
            "name": "MoM Cash Flow Color",
            "expression": [
              "",
              "VAR MaxDate =",
              "    MAX('DimDate'[Date])",
              "",
              "-- Current month boundaries",
              "VAR ST_CURR = EOMONTH(MaxDate, -1) + 1",
              "VAR END_CURR = MaxDate",
              "",
              "-- Previous month boundaries",
              "VAR ST_PREV = EOMONTH(MaxDate, -2) + 1",
              "VAR END_PREV = EOMONTH(MaxDate, -1)",
              "",
              "-- Current month CF",
              "VAR CF_CURR =",
              "    CALCULATE(",
              "        [Cash Flow],",
              "        DATESBETWEEN('DimDate'[Date], ST_CURR, END_CURR)",
              "    )",
              "",
              "-- Previous month CF",
              "VAR CF_PREV =",
              "    CALCULATE(",
              "        [Cash Flow],",
              "        DATESBETWEEN('DimDate'[Date], ST_PREV, END_PREV)",
              "    )",
              "",
              "VAR _pctchange = DIVIDE(CF_CURR - CF_PREV, CF_PREV, 0)",
              "",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(CF_PREV), \"#808080\",     -- No previous month",
              "    _pctchange > 0, \"#008000\",       -- Green (increase)",
              "    _pctchange < 0, \"#FF0000\",       -- Red (decline)",
              "    \"#000000\"                        -- Black (no change)",
              ")"
            ],
            "displayFolder": "TIMESERIES",
            "lineageTag": "ccfaf488-acfc-4182-bc16-1bff3b808faa"
          },
          {
            "name": "MoM Profit Color",
            "expression": [
              "",
              "VAR MaxDate =",
              "    MAX('DimDate'[Date])",
              "",
              "-- Current month boundaries",
              "VAR ST_CURR = EOMONTH(MaxDate, -1) + 1",
              "VAR END_CURR = MaxDate",
              "",
              "-- Previous month boundaries",
              "VAR ST_PREV = EOMONTH(MaxDate, -2) + 1",
              "VAR END_PREV = EOMONTH(MaxDate, -1)",
              "",
              "-- Current month profit",
              "VAR PROF_CURR =",
              "    CALCULATE(",
              "        [Net Profit],",
              "        DATESBETWEEN('DimDate'[Date], ST_CURR, END_CURR)",
              "    )",
              "",
              "-- Previous month profit",
              "VAR PROF_PREV =",
              "    CALCULATE(",
              "        [Net Profit],",
              "        DATESBETWEEN('DimDate'[Date], ST_PREV, END_PREV)",
              "    )",
              "",
              "VAR _pctchange = DIVIDE(PROF_CURR - PROF_PREV, PROF_PREV, 0)",
              "",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(PROF_PREV), \"#808080\",   -- No previous month",
              "    _pctchange > 0, \"#008000\",       -- Increase = green",
              "    _pctchange < 0, \"#FF0000\",       -- Decrease = red",
              "    \"#000000\"                        -- No change",
              ")"
            ],
            "displayFolder": "TIMESERIES",
            "lineageTag": "a4d2c212-1fed-4913-be0c-46cfd67f52eb"
          },
          {
            "name": "Most Expensive Payment Method",
            "expression": [
              "",
              "VAR MaxFeeMethod =",
              "    TOPN(",
              "        1,",
              "        SUMMARIZE(",
              "            FactPayment,",
              "            DimPaymentMethod[PaymentMethod],",
              "            \"TotalFees\", [Payment Fees Total]",
              "        ),",
              "        [TotalFees],",
              "        DESC",
              "    )",
              "VAR MethodName =",
              "    MAXX(MaxFeeMethod, DimPaymentMethod[PaymentMethod])",
              "RETURN",
              "    \"Most Expensive Payment Method is: \" & MethodName"
            ],
            "displayFolder": "BREAKDOWN MEASURES",
            "lineageTag": "1f4c92f9-b5ea-4630-a85b-1a4bdaa30bc8"
          },
          {
            "name": "Payment Details - Avg Days Outstanding",
            "expression": [
              "",
              "VAR FilteredPayments = ",
              "    FILTER(",
              "        FactPayment,",
              "        FactPayment[PaymentStatus] IN {\"Pending\", \"Failed\"}",
              "    )",
              "RETURN",
              "    AVERAGEX(",
              "        FilteredPayments,",
              "        DATEDIFF(FactPayment[PaymentDate], TODAY(), DAY)",
              "    )",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "DRILL-THROUGH",
            "lineageTag": "86e98396-5d48-4103-b550-eceade2ccb63"
          },
          {
            "name": "Payment Details - Total Amount",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(FactPayment[PaymentAmount])",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "displayFolder": "DRILL-THROUGH",
            "lineageTag": "0c8fb33a-8ab8-4ad9-a864-1c0c3bc829ad"
          },
          {
            "name": "Payment Details - Oldest Payment Days",
            "expression": [
              "",
              "VAR FilteredPayments = ",
              "    FILTER(",
              "        FactPayment,",
              "        FactPayment[PaymentStatus] IN {\"Pending\", \"Failed\"}",
              "    )",
              "RETURN",
              "    MAXX(",
              "        FilteredPayments,",
              "        DATEDIFF(FactPayment[PaymentDate], MAX(FactPayment[PaymentDate]), DAY)",
              "    )"
            ],
            "formatString": "0",
            "displayFolder": "DRILL-THROUGH",
            "lineageTag": "3911bdcf-ea45-4b31-877b-506f1c5ebfea"
          },
          {
            "name": "Payment Details - Transaction Count",
            "expression": [
              "",
              "COUNTROWS(FactPayment)"
            ],
            "formatString": "0",
            "displayFolder": "DRILL-THROUGH",
            "lineageTag": "e1eac65c-e9b7-44d2-92b6-a2ebc3acb2c2"
          },
          {
            "name": "Payment Aging - 0-15 Days",
            "expression": [
              "",
              "VAR Today = MAX(FactPayment[PaymentDate])",
              "RETURN",
              "    CALCULATE(",
              "        SUM(FactPayment[PaymentAmount]),",
              "        FactPayment[PaymentStatus] IN {\"Pending\", \"Failed\"},",
              "        FILTER(",
              "            FactPayment,",
              "            DATEDIFF(FactPayment[PaymentDate], MAX(FactPayment[PaymentDate]), DAY) <= 15",
              "        )",
              "    )"
            ],
            "formatString": "\"Rs\"#,0.###############;-\"Rs\"#,0.###############;\"Rs\"#,0.###############",
            "displayFolder": "DRILL-THROUGH",
            "lineageTag": "3ec90158-ebf2-4d18-af80-f8d627f11f17",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-PK\"}"
              }
            ]
          },
          {
            "name": "Payment Aging - 16-30 Days",
            "expression": [
              "",
              "VAR Today = MAX(FactPayment[PaymentDate])",
              "RETURN",
              "    CALCULATE(",
              "        SUM(FactPayment[PaymentAmount]),",
              "        FactPayment[PaymentStatus] IN {\"Pending\", \"Failed\"},",
              "        FILTER(",
              "            FactPayment,",
              "            DATEDIFF(FactPayment[PaymentDate], MAX(FactPayment[PaymentDate]), DAY) > 15 &&",
              "            DATEDIFF(FactPayment[PaymentDate], MAX(FactPayment[PaymentDate]), DAY) <= 30",
              "        )",
              "    )"
            ],
            "formatString": "\"Rs\"#,0.###############;-\"Rs\"#,0.###############;\"Rs\"#,0.###############",
            "displayFolder": "DRILL-THROUGH",
            "lineageTag": "5acf2f89-2afd-4dc6-9efb-a464eb71d6b9",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-PK\"}"
              }
            ]
          },
          {
            "name": "Payment Aging - 31-60 Days",
            "expression": [
              "",
              "VAR Today = MAX(FactPayment[PaymentDate])",
              "RETURN",
              "    CALCULATE(",
              "        SUM(FactPayment[PaymentAmount]),",
              "        FactPayment[PaymentStatus] IN {\"Pending\", \"Failed\"},",
              "        FILTER(",
              "            FactPayment,",
              "            DATEDIFF(FactPayment[PaymentDate], MAX(FactPayment[PaymentDate]), DAY) > 30 &&",
              "            DATEDIFF(FactPayment[PaymentDate], MAX(FactPayment[PaymentDate]), DAY) <= 60",
              "        )",
              "    )",
              ""
            ],
            "formatString": "\"Rs\"#,0.###############;-\"Rs\"#,0.###############;\"Rs\"#,0.###############",
            "displayFolder": "DRILL-THROUGH",
            "lineageTag": "bb5afe1c-d5f4-414b-b624-68b70beb6fe7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-PK\"}"
              }
            ]
          },
          {
            "name": "Payment Aging - 60+ Days",
            "expression": [
              "",
              "VAR Today = MAX(FactPayment[PaymentDate])",
              "RETURN",
              "    CALCULATE(",
              "        SUM(FactPayment[PaymentAmount]),",
              "        FactPayment[PaymentStatus] IN {\"Pending\", \"Failed\"},",
              "        FILTER(",
              "            FactPayment,",
              "            DATEDIFF(FactPayment[PaymentDate], MAX(FactPayment[PaymentDate]), DAY) > 60",
              "        )",
              "    )"
            ],
            "formatString": "\"Rs\"#,0.###############;-\"Rs\"#,0.###############;\"Rs\"#,0.###############",
            "displayFolder": "DRILL-THROUGH",
            "lineageTag": "339222ab-5350-4ccd-9972-ae12eb861c5c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-PK\"}"
              }
            ]
          },
          {
            "name": "Payment Aging - Amount",
            "expression": [
              "",
              "VAR SelectedBucket = SELECTEDVALUE('Payment Aging Categories'[AgingBucket])",
              "RETURN",
              "    SWITCH(",
              "        SelectedBucket,",
              "        \"0-15 Days\", [Payment Aging - 0-15 Days],",
              "        \"16-30 Days\", [Payment Aging - 16-30 Days],",
              "        \"31-60 Days\", [Payment Aging - 31-60 Days],",
              "        \"60+ Days\", [Payment Aging - 60+ Days],",
              "        BLANK()",
              "    )"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "displayFolder": "DRILL-THROUGH",
            "lineageTag": "067af158-9b6e-47c7-93c4-590f337915e8"
          },
          {
            "name": "Location Color",
            "expression": [
              "",
              "VAR _table =",
              "    SUMMARIZE(",
              "        ALLSELECTED('DimLocation'),",
              "        'DimLocation'[Location],",
              "        \"RevenueValue\", [Total Income]",
              "    )",
              "VAR _maxval = MAXX(_table, [RevenueValue])",
              "VAR _minval = MINX(_table, [RevenueValue])",
              "VAR _currval = [Total income]",
              "",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    _currval = _maxval, \"Green\",   -- Green (Best)",
              "    _currval = _minval, \"Red\",   -- Red (Worst)",
              "    \"Light Grey\"                        -- Grey (Others)",
              ")",
              ""
            ],
            "displayFolder": "Format",
            "lineageTag": "192e7ef4-e16d-4891-b2ba-c084b8ddb56c"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Payment Aging Categories",
        "lineageTag": "7aa266c6-fa86-45d6-be9f-8ae8827cf052",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "AgingBucket",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[AgingBucket]",
            "lineageTag": "589438b1-3aa7-4cfd-9253-a49ece45ff47",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "SortOrder",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[SortOrder]",
            "formatString": "0",
            "lineageTag": "9e3c1a1c-5a9c-4273-aab5-073356e65437",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Payment Aging Categories",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "DATATABLE(",
                "    \"AgingBucket\", STRING,",
                "    \"SortOrder\", INTEGER,",
                "    {",
                "        {\"0-15 Days\", 1},",
                "        {\"16-30 Days\", 2},",
                "        {\"31-60 Days\", 3},",
                "        {\"60+ Days\", 4}",
                "    }",
                ")"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "e64a7b63f9774157a931cdf70754d3fc"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "AutoDetected_fdefa621-7e6c-4a67-b7d6-94b9209d4bc0",
        "fromTable": "FactExpense",
        "fromColumn": "ExpCategoryKey",
        "toTable": "DimExpCategory",
        "toColumn": "ExpCategoryKey"
      },
      {
        "name": "AutoDetected_2051b95c-6531-4081-bf9e-d8555fe4d110",
        "fromTable": "FactExpense",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "1f60e099-ef59-0f1c-838f-bab2e2e4dae8",
        "fromTable": "FactPayment",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "629a9fff-e65d-3055-f45f-b4b0508f2db2",
        "fromTable": "FactSalesHeader",
        "fromColumn": "PaymentMethodKey",
        "toTable": "DimPaymentMethod",
        "toColumn": "PaymentMethodKey"
      },
      {
        "name": "e2e13db1-91f7-2fb4-0702-0716bb51bc7c",
        "fromTable": "FactSalesHeader",
        "fromColumn": "LocationKey",
        "toTable": "DimLocation",
        "toColumn": "LocationKey"
      },
      {
        "name": "267c6a04-1d18-daa5-540b-7f9277cf6134",
        "fromTable": "FactSalesHeader",
        "fromColumn": "CustomerKey",
        "toTable": "DimCustomer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "50639fff-b93a-10f5-e984-c9b6286257fc",
        "fromTable": "FactSalesLine",
        "fromColumn": "ProductKey",
        "toTable": "DimProduct",
        "toColumn": "ProductKey"
      },
      {
        "name": "be52c9fa-422c-b6f4-ad8e-ba79a5d09d08",
        "fromTable": "FactSalesHeader",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "64f05415-2f8c-edcc-985a-a6d9fd722074",
        "fromTable": "FactSalesHeader",
        "fromColumn": "SalesHeaderKey",
        "toTable": "FactSalesLine",
        "toColumn": "SalesHeaderKey"
      },
      {
        "name": "929265d4-0071-2c46-f082-fbfb0941c2c2",
        "fromTable": "FactPayment",
        "fromColumn": "PaymentMethodKey",
        "toTable": "DimPaymentMethod",
        "toColumn": "PaymentMethodKey"
      },
      {
        "name": "aa008d37-80bb-cebf-bc6f-72c123ee07da",
        "fromTable": "FactSalesLine",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "expressions": [
      {
        "name": "pDataFolderPath",
        "description": "Path to the source data folder",
        "kind": "m",
        "expression": "\"D:\\Power BI\\PowerBI_Bakery_Project\\01_SourceData\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "queryGroup": "01_Parameters",
        "lineageTag": "31610c7a-0ef3-4c5e-8e1e-6d2962511455",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ]
      },
      {
        "name": "fnclean_sales",
        "kind": "m",
        "expression": [
          "(file as binary) as table =>",
          "let",
          "    // --- Step 1: Read file as text",
          "    Source = Text.FromBinary(file, TextEncoding.Utf8),",
          "",
          "    // --- Step 2: Split into lines",
          "    Lines = Lines.FromText(Source),",
          "",
          "    // --- Step 3: Remove empty lines",
          "    NonEmptyLines = List.Select(Lines, each Text.Trim(_) <> \"\"),",
          "",
          "    // --- Step 4: Remove junk/report lines",
          "    CleanLines = List.Select(",
          "        NonEmptyLines,",
          "        each not Text.StartsWith(_, \"Report Generated\")",
          "             and not Text.StartsWith(_, \"Sales Export\")",
          "    ),",
          "",
          "    // --- Step 5: Standardize header lines",
          "    StandardHeader = \"OrderID,CustomerID,ProductID,OrderDate,Quantity,UnitPrice,Discount,Tax,PaymentMethod,Location,LeadTime,OrderStatus\",",
          "    FixedHeaders = List.Transform(",
          "        CleanLines,",
          "        each if Text.Contains(_, \"Order ID\") ",
          "             or Text.Contains(_, \"SalesOrderID\") ",
          "             or Text.Contains(_, \"Unit Price\") ",
          "             or Text.Contains(_, \"Price\")",
          "             or Text.Contains(_, \"ProdID\") then StandardHeader else _",
          "    ),",
          "",
          "    // --- Step 6: Keep only data lines (header + rows)",
          "    DataLines = List.Select(",
          "        FixedHeaders,",
          "        each Text.Contains(_, \"OrderID\") or Text.Contains(_, \"ORD-\")",
          "    ),",
          "",
          "    // --- Step 7: Recombine into CSV",
          "    RebuiltCSV = Text.Combine(DataLines, \"#(lf)\"),",
          "    CsvTable = Csv.Document(RebuiltCSV, [Delimiter=\",\", Encoding=65001]),",
          "",
          "    // --- Step 8: Promote headers",
          "    PromotedHeaders = Table.PromoteHeaders(CsvTable, [PromoteAllScalars=true]),",
          "",
          "    // --- Step 9: Rename all column variants to standard names",
          "    RenamedColumns = Table.RenameColumns(",
          "        PromotedHeaders,",
          "        {",
          "            {\"Unit Price\", \"UnitPrice\"},",
          "            {\"Price\", \"UnitPrice\"},",
          "            {\"Tax Amount\", \"Tax\"},",
          "            {\"ProdID\", \"ProductID\"}",
          "        },",
          "        MissingField.Ignore",
          "    ),",
          "",
          "    // --- Step 10: Clean numeric columns safely",
          "    CleanNumeric = Table.TransformColumns(",
          "        RenamedColumns,",
          "        {",
          "            {\"UnitPrice\", each try Number.From(Text.Select(Text.From(_), {\"0\"..\"9\",\".\",\"-\"})) otherwise null, type number},",
          "            {\"Discount\", each try Number.From(Text.Select(Text.From(_), {\"0\"..\"9\",\".\",\"-\"})) otherwise null, type number},",
          "            {\"Tax\", each try Number.From(Text.Select(Text.From(_), {\"0\"..\"9\",\".\",\"-\"})) otherwise null, type number}",
          "        }",
          "    ),",
          "",
          "    // --- Step 11: Convert other types",
          "    FinalTable = Table.TransformColumnTypes(",
          "        CleanNumeric,",
          "        {",
          "            {\"OrderID\", type text},",
          "            {\"CustomerID\", type text},",
          "            {\"ProductID\", type text},",
          "            {\"OrderDate\", type date},",
          "            {\"Quantity\", Int64.Type},",
          "            {\"PaymentMethod\", type text},",
          "            {\"Location\", type text},",
          "            {\"LeadTime\", Int64.Type},",
          "            {\"OrderStatus\", type text}",
          "        }",
          "    )",
          "in",
          "    FinalTable"
        ],
        "queryGroup": "02_Functions",
        "lineageTag": "41ecc87b-6e69-4a32-a216-7d532b0c2cbb",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ]
      },
      {
        "name": "stgSales_Combined",
        "kind": "m",
        "expression": [
          "let",
          "    Source = Folder.Files(pDataFolderPath & \"\\Sales\\\"),",
          "    #\"Added Custom\" = Table.AddColumn(Source, \"Data\", each fnclean_sales([Content])),",
          "    #\"Added Custom1\" = Table.AddColumn(#\"Added Custom\", \"Custom\", each Text.Start(Text.FromBinary([Content]),200)),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Custom1\",{\"Custom\"}),",
          "    #\"Expanded Data\" = Table.ExpandTableColumn(#\"Removed Columns\", \"Data\", {\"OrderID\", \"CustomerID\", \"ProductID\", \"OrderDate\", \"Quantity\", \"UnitPrice\", \"Discount\", \"Tax\", \"PaymentMethod\", \"Location\", \"LeadTime\", \"OrderStatus\"}, {\"OrderID\", \"CustomerID\", \"ProductID\", \"OrderDate\", \"Quantity\", \"UnitPrice\", \"Discount\", \"Tax\", \"PaymentMethod\", \"Location\", \"LeadTime\", \"OrderStatus\"}),",
          "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Expanded Data\",{\"Content\", \"Extension\", \"Date accessed\", \"Date modified\", \"Date created\", \"Attributes\", \"Folder Path\"}),",
          "    #\"Added Custom2\" = Table.AddColumn(#\"Removed Columns1\", \"Custom\", each let",
          "    DateText = Text.Middle([Name], 6, 8),",
          "    Year = Text.Start(DateText, 4),",
          "    Month = Text.Range(DateText, 4, 2),",
          "    Day = Text.End(DateText, 2)",
          "in",
          "    Date.FromText(Year & \"-\" & Month & \"-\" & Day)),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom2\",{{\"Custom\", type date}}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"OrderDate\", \"OrderDate 1\"}, {\"Custom\", \"OrderDate\"}}),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Renamed Columns\",{\"Name\", \"OrderID\", \"CustomerID\", \"ProductID\", \"OrderDate\", \"OrderDate 1\", \"Quantity\", \"UnitPrice\", \"Discount\", \"Tax\", \"PaymentMethod\", \"Location\", \"LeadTime\", \"OrderStatus\"}),",
          "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Reordered Columns\",{\"OrderDate 1\"})",
          "in",
          "    #\"Removed Columns2\""
        ],
        "queryGroup": "03_Staging - Sales",
        "lineageTag": "fbfdd9f8-6bf7-458c-a2c5-eda7a75ec4f4",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "stgExpenses",
        "kind": "m",
        "expression": [
          "let",
          "    // Connect to Expenses folder",
          "    Source = Folder.Files(pDataFolderPath & \"\\Expenses\\\"),",
          "    FilterCSV = Table.SelectRows(Source, each [Extension] = \".csv\"),",
          "    ",
          "    // Load each CSV file",
          "    AddedData = Table.AddColumn(FilterCSV, \"Data\", each",
          "        let",
          "            LoadedCSV = Csv.Document([Content]),",
          "            Promoted = Table.PromoteHeaders(LoadedCSV, [PromoteAllScalars=true])",
          "        in",
          "            Promoted",
          "    ),",
          "    ",
          "    // Expand columns",
          "    ExpandedData = Table.ExpandTableColumn(",
          "        AddedData,",
          "        \"Data\",",
          "        {\"ExpenseID\", \"CategoryName\", \"ExpenseAmount\", \"ExpenseDate\", \"VendorName\", \"Description\"}",
          "    ),",
          "    ",
          "    // FIX DATE FORMAT - Same as Customer fix",
          "    FixedDate = Table.TransformColumns(ExpandedData, {",
          "        {\"ExpenseDate\", each ",
          "            if _ <> null and _ <> \"\" then",
          "                Date.FromText(_, [Format=\"MM/dd/yyyy\"])",
          "            else",
          "                null,",
          "            type date",
          "        }",
          "    }),",
          "    ",
          "    // Change other types",
          "    ChangedTypes = Table.TransformColumnTypes(FixedDate, {",
          "        {\"ExpenseID\", type text},",
          "        {\"CategoryName\", type text},",
          "        {\"ExpenseAmount\", type number},",
          "        {\"VendorName\", type text},",
          "        {\"Description\", type text}",
          "    }),",
          "    ",
          "    // Remove extra columns (keep only data columns)",
          "    RemovedColumns = Table.SelectColumns(ChangedTypes, {",
          "        \"ExpenseID\", \"CategoryName\", \"ExpenseAmount\", \"ExpenseDate\", \"VendorName\", \"Description\"",
          "    })",
          "in",
          "    RemovedColumns"
        ],
        "queryGroup": "07_Staging - Expenses",
        "lineageTag": "56cc22f8-2798-4cbf-97b2-c2136b8a1f32",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "stgProduct_Combined",
        "kind": "m",
        "expression": [
          "let",
          "    // Connect to Products folder",
          "    Source = Folder.Files(pDataFolderPath & \"\\Products\\\"),",
          "    FilterCSV = Table.SelectRows(Source, each [Extension] = \".csv\"),",
          "    ",
          "    // Load and clean each file",
          "    AddedData = Table.AddColumn(FilterCSV, \"Data\", each",
          "        let",
          "            LoadedCSV = Csv.Document([Content]),",
          "            Promoted = Table.PromoteHeaders(LoadedCSV, [PromoteAllScalars=true])",
          "        in",
          "            Promoted",
          "    ),",
          "    ",
          "    // Expand",
          "    ExpandedData = Table.ExpandTableColumn(AddedData, \"Data\", ",
          "        {\"ProductID\", \"ProductName\", \"Category\", \"SubCategory\", \"UnitCost\", \"CurrentPrice\", \"IsActive\"}",
          "    ),",
          "    ",
          "    // Sort by filename descending (latest snapshot first)",
          "    Sorted = Table.Sort(ExpandedData, {{\"Name\", Order.Descending}}),",
          "    ",
          "    // Remove duplicates (keep latest ProductID only)",
          "    RemovedDuplicates = Table.Distinct(Sorted, {\"ProductID\"}),",
          "    ",
          "    // Generate ProductKey using index",
          "    AddedProductKey = Table.AddIndexColumn(RemovedDuplicates, \"ProductKey\", 1, 1, Int64.Type),",
          "    ",
          "    // Add Unknown row",
          "    UnknownRow = #table(",
          "        {\"ProductKey\", \"ProductID\", \"ProductName\", \"Category\", \"SubCategory\", \"UnitCost\", \"CurrentPrice\", \"IsActive\"},",
          "        {{-1, \"UNKNOWN\", \"Unknown Product\", \"Unknown\", \"Unknown\", 0, 0, \"No\"}}",
          "    ),",
          "    ",
          "    // Combine",
          "    Combined = Table.Combine({UnknownRow, AddedProductKey}),",
          "    ",
          "    // Select final columns",
          "    FinalColumns = Table.SelectColumns(Combined, ",
          "        {\"ProductKey\", \"ProductID\", \"ProductName\", \"Category\", \"SubCategory\", \"UnitCost\", \"CurrentPrice\", \"IsActive\"}",
          "    ),",
          "    ",
          "    // Change types",
          "    ChangedTypes = Table.TransformColumnTypes(FinalColumns, {",
          "        {\"ProductKey\", Int64.Type},",
          "        {\"ProductID\", type text},",
          "        {\"ProductName\", type text},",
          "        {\"Category\", type text},",
          "        {\"SubCategory\", type text},",
          "        {\"UnitCost\", type number},",
          "        {\"CurrentPrice\", type number},",
          "        {\"IsActive\", type text}",
          "    })",
          "in",
          "    ChangedTypes"
        ],
        "queryGroup": "05_Staging - Products",
        "lineageTag": "d58af9f1-4544-4bed-8b5c-3af5464bd1c6",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "stgCustomer_Combined",
        "kind": "m",
        "expression": [
          "let",
          "    // Connect to Customers folder",
          "    Source = Folder.Files(pDataFolderPath & \"\\Customers\\\"),",
          "    FilterCSV = Table.SelectRows(Source, each [Extension] = \".csv\"),",
          "    ",
          "    // Load and clean each file",
          "    AddedData = Table.AddColumn(FilterCSV, \"Data\", each",
          "        let",
          "            LoadedCSV = Csv.Document([Content]),",
          "            Promoted = Table.PromoteHeaders(LoadedCSV, [PromoteAllScalars=true])",
          "        in",
          "            Promoted",
          "    ),",
          "    ",
          "    // Expand",
          "    ExpandedData = Table.ExpandTableColumn(",
          "        AddedData,",
          "        \"Data\",",
          "        {\"CustomerID\", \"CustomerName\", \"CustomerType\", \"Email\", \"Phone\", \"RegistrationDate\", \"IsActive\"}",
          "    ),",
          "    ",
          "    // Sort by filename descending (latest snapshot first)",
          "    Sorted = Table.Sort(ExpandedData, {{\"Name\", Order.Descending}}),",
          "    ",
          "    // Remove duplicates (keep latest CustomerID only)",
          "    RemovedDuplicates = Table.Distinct(Sorted, {\"CustomerID\"}),",
          "    ",
          "    // Generate CustomerKey using index",
          "    AddedCustomerKey = Table.AddIndexColumn(RemovedDuplicates, \"CustomerKey\", 1, 1, Int64.Type),",
          "",
          "    // Add Unknown row",
          "    UnknownRow = #table(",
          "        {\"CustomerKey\", \"CustomerID\", \"CustomerName\", \"CustomerType\", \"Email\", \"Phone\", \"RegistrationDate\", \"IsActive\"},",
          "        {{-1, \"UNKNOWN\", \"Unknown Customer\", \"Unknown\", \"\", \"\", #date(2022,1,1), \"No\"}}",
          "    ),",
          "    ",
          "    // Combine",
          "    Combined = Table.Combine({UnknownRow, AddedCustomerKey}),",
          "    ",
          "    // Select final columns",
          "    FinalColumns = Table.SelectColumns(",
          "        Combined,",
          "        {\"CustomerKey\", \"CustomerID\", \"CustomerName\", \"CustomerType\", \"Email\", \"Phone\", \"RegistrationDate\", \"IsActive\"}",
          "    ),",
          "",
          "    // 🔹 FIX STARTS HERE — Safe Date Parsing",
          "    ForceText = Table.TransformColumnTypes(FinalColumns, {",
          "        {\"RegistrationDate\", type text}",
          "    }),",
          "",
          "    ParsedDate = Table.AddColumn(",
          "        ForceText,",
          "        \"RegistrationDate_Clean\",",
          "        each",
          "            let",
          "                CleanText = Text.Trim([RegistrationDate])",
          "            in",
          "                if CleanText = null or CleanText = \"\" then null",
          "                else if Text.Contains(CleanText, \"-\") then",
          "                    try Date.FromText(CleanText) otherwise null",
          "                else if Text.Contains(CleanText, \"/\") then",
          "                    let",
          "                        Parts = Text.Split(CleanText, \"/\"),",
          "                        P1 = Number.FromText(Parts{0}),",
          "                        P2 = Number.FromText(Parts{1}),",
          "                        P3 = Number.FromText(Parts{2})",
          "                    in",
          "                        if P1 > 12 then",
          "                            #date(P3, P2, P1)",
          "                        else",
          "                            #date(P3, P1, P2)",
          "                else null,",
          "        type date",
          "    ),",
          "",
          "    RemovedOld = Table.RemoveColumns(ParsedDate, {\"RegistrationDate\"}),",
          "",
          "    Renamed = Table.RenameColumns(RemovedOld, {",
          "        {\"RegistrationDate_Clean\", \"RegistrationDate\"}",
          "    }),",
          "    // 🔹 FIX ENDS HERE",
          "",
          "    // Change final types",
          "    ChangedTypes = Table.TransformColumnTypes(Renamed, {",
          "        {\"CustomerKey\", Int64.Type},",
          "        {\"CustomerID\", type text},",
          "        {\"CustomerName\", type text},",
          "        {\"CustomerType\", type text},",
          "        {\"Email\", type text},",
          "        {\"Phone\", type text},",
          "        {\"RegistrationDate\", type date},",
          "        {\"IsActive\", type text}",
          "    }),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(ChangedTypes,{\"CustomerKey\", \"CustomerID\", \"CustomerName\", \"CustomerType\", \"Email\", \"Phone\", \"RegistrationDate\", \"IsActive\"})",
          "in",
          "    #\"Reordered Columns\""
        ],
        "queryGroup": "06_Staging - Customers",
        "lineageTag": "2b0558db-df85-49d8-ba07-ef42957417ef",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "stgPayments_Combined",
        "kind": "m",
        "expression": [
          "let",
          "    // Connect to Payments folder",
          "    Source = Folder.Files(pDataFolderPath & \"\\Payments\\\"),",
          "    FilterCSV = Table.SelectRows(Source, each [Extension] = \".csv\"),",
          "    ",
          "    // Load each file (no junk headers - files are clean)",
          "    AddedData = Table.AddColumn(FilterCSV, \"Data\", each",
          "        let",
          "            LoadedCSV = Csv.Document([Content]),",
          "            Promoted = Table.PromoteHeaders(LoadedCSV, [PromoteAllScalars=true])",
          "        in",
          "            Promoted",
          "    ),",
          "    ",
          "    // Expand columns",
          "    ExpandedData = Table.ExpandTableColumn(",
          "        AddedData,",
          "        \"Data\",",
          "        {\"PaymentID\", \"SalesOrderID\", \"PaymentAmount\", \"PaymentDate\", \"PaymentStatus\", \"PaymentMethod\", \"FeeAmount\", \"ReconciliationDate\"}",
          "    ),",
          "    ",
          "    // Add SourceFileName",
          "    AddedSourceFile = Table.RenameColumns(",
          "        Table.SelectColumns(ExpandedData, {\"Name\", \"PaymentID\", \"SalesOrderID\", \"PaymentAmount\", \"PaymentDate\", \"PaymentStatus\", \"PaymentMethod\", \"FeeAmount\", \"ReconciliationDate\"}),",
          "        {{\"Name\", \"SourceFileName\"}}",
          "    ),",
          "    ",
          "    // FIX DATES - PaymentDate",
          "    FixedPaymentDate = Table.TransformColumns(AddedSourceFile, {",
          "        {\"PaymentDate\", each ",
          "            if _ <> null and _ <> \"\" then",
          "                Date.FromText(_, [Format=\"MM/dd/yyyy\"])",
          "            else",
          "                null,",
          "            type date",
          "        }",
          "    }),",
          "    ",
          "    // FIX DATES - ReconciliationDate (can be empty)",
          "    FixedReconciliationDate = Table.TransformColumns(FixedPaymentDate, {",
          "        {\"ReconciliationDate\", each ",
          "            if _ <> null and _ <> \"\" then",
          "                Date.FromText(_, [Format=\"MM/dd/yyyy\"])",
          "            else",
          "                null,",
          "            type date",
          "        }",
          "    }),",
          "    ",
          "    // Change other types",
          "    ChangedTypes = Table.TransformColumnTypes(FixedReconciliationDate, {",
          "        {\"PaymentID\", type text},",
          "        {\"SalesOrderID\", type text},",
          "        {\"PaymentAmount\", type number},",
          "        {\"PaymentStatus\", type text},",
          "        {\"PaymentMethod\", type text},",
          "        {\"FeeAmount\", type number},",
          "        {\"SourceFileName\", type text}",
          "    }),",
          "    ",
          "    // Add IsReconciled flag (TRUE if status = \"Received\")",
          "    AddedIsReconciled = Table.AddColumn(ChangedTypes, \"IsReconciled\", each ",
          "        [PaymentStatus] = \"Received\",",
          "        type logical",
          "    ),",
          "    ",
          "    // Add LoadDateTime",
          "    AddedLoadDateTime = Table.AddColumn(AddedIsReconciled, \"LoadDateTime\", each ",
          "        DateTime.LocalNow(), ",
          "        type datetime",
          "    ),",
          "    ",
          "    // Final column order",
          "    ReorderedColumns = Table.SelectColumns(AddedLoadDateTime, {",
          "        \"PaymentID\", \"SalesOrderID\", \"PaymentAmount\", \"PaymentDate\", ",
          "        \"PaymentStatus\", \"PaymentMethod\", \"FeeAmount\", \"ReconciliationDate\",",
          "        \"IsReconciled\", \"SourceFileName\", \"LoadDateTime\"",
          "    }),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(ReorderedColumns,{{\"PaymentAmount\", Currency.Type}, {\"FeeAmount\", Currency.Type}}),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Changed Type\",{\"SourceFileName\", \"PaymentID\", \"SalesOrderID\", \"PaymentAmount\", \"PaymentDate\", \"PaymentStatus\", \"PaymentMethod\", \"FeeAmount\", \"ReconciliationDate\", \"IsReconciled\", \"LoadDateTime\"})",
          "in",
          "    #\"Reordered Columns\""
        ],
        "queryGroup": "04_Staging - Payments",
        "lineageTag": "2b336573-8391-4e92-a0f5-25013ac980cc",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "queryGroups": [
      {
        "folder": "01_Parameters",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ]
      },
      {
        "folder": "08_Dimension Tables",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "8"
          }
        ]
      },
      {
        "folder": "02_Functions",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ]
      },
      {
        "folder": "03_Staging - Sales",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ]
      },
      {
        "folder": "04_Staging - Payments",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "4"
          }
        ]
      },
      {
        "folder": "05_Staging - Products",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "5"
          }
        ]
      },
      {
        "folder": "06_Staging - Customers",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "6"
          }
        ]
      },
      {
        "folder": "07_Staging - Expenses",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "7"
          }
        ]
      },
      {
        "folder": "9_Fact Tables",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "9"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"pDataFolderPath\",\"DimCustomer\",\"DimProduct\",\"DimDate\",\"fnclean_sales\",\"stgSales_Combined\",\"stgProduct_Combined\",\"stgCustomer_Combined\",\"DimPaymentMethod\",\"DimLocation\",\"FactSalesHeader\",\"FactSalesLine\",\"stgExpenses\",\"DimExpCategory\",\"stgPayments_Combined\",\"FactPayment\",\"FactExpense\",\"_Measures\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"TMDLView_Desktop\"]"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"SortArrays\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Shared Expressions\",\"Perspectives\",\"Relationships\",\"Roles\",\"Tables\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Tables/Calculation Items\",\"Translations\"]}"
      }
    ]
  }
}